### ISSUE TITLE
Possible namespace issue?

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#10]
After installing the ISRaD pkg I noticed that even base R functions (e.g. seq) were no longer storing data in the assigned objects. I removed the ISRaD package and it seemed to fix the problem. Any insight?

**Comment by greymonroe** [comment]
Hmm, thanks. Can you reinstall from github:

```install_github("International-Soil-Radiocarbon-Database/ISRaD")```

try to reproduce the issue and send me the code?

**Comment by jb388** [comment]
Yes, I did reinstall. Here's the code:

devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD")
library(ISRaD)
scd.mpi2 <- compile("/Users/jeff/R/israd/depthneg/All/", write_report = T, write_out = T)
# using local directory
str(scd.mpi2) # returns blank object

# test base R fxn
a <- seq(1:10)
a # returns blank object

**Comment by greymonroe** [comment]
k what about ?
```
sink(type="message")
sink()
sink(type="message")
sink()
sink(type="message")
sink()
a
```

**Comment by greymonroe** [comment]
See issue #9 for explanation. Generally, if this happens, it means the QAQC report had an error which halts everything such that R continues to try to write all output to the report file. **For a quick fix you can run** 
```
sink(type="message")
sink()
```
**a few times** to close the connection to the report file and get back to working in R immediately. You should then check the last QAQC report file to see the error that is causing the problem and we can start working on it from there to get at the underlying issue.

**Comment by jb388** [comment]
Ah, good to know. I resorted to reinstalling R several times to fix it.

**Comment by greymonroe** [comment]
ouch, sorry for the headache!
