### ISSUE TITLE
Depth convention not specified on interstitial tab

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#102]
We should add a column similar to the layer "lyr_all_org_neg" on the layer tab to the interstitial tab. This tab links to the profile layer, so currently the depth convention is not specified. 

This is particularly relevant since many peatland datasets have interstitial data and will be using the alternate depth convention

**Comment by jb388** [comment]
This change seemed necessary and since there were no further comments I went ahead and added the field "ist_all_org_neg" to the interstitial tab of the template and to the template info file.
