### ISSUE TITLE
Handling anaerobic incubations

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#103]
Currently template assuming incubations are aerobic, and flux is only CO2.

Would be nice to handle anaerobic incubations, and flux and 14C values could be those of CH4 or CO2.

One option to do this would be to add two new non-required columns where blank defaults to aerobic/CO2:
1) inc_anaerobic: would be yes or blank (blank is aerobic)
2) inc_analyte: would be CH4 or blank, where blank defaults to CO2

Alternatively there could be other better ways of dealing with this as well?

**Comment by jb388** [comment]
This approach sounds good to me. I will plan to implement at the end of this week (30 Nov.) unless I hear otherwise.

**Comment by aahoyt** [comment]
We are working on a template with this issue today, and it looks like maybe this never got implemented?

**Comment by jb388** [comment]
implemented
