### ISSUE TITLE
ISRaD.extra produces warnings

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#104]
Warning messages:
1: Column `entry_name` joining factors with different levels, coercing to character vector
2: Column `site_name` joining factors with different levels, coercing to character vector
3: Column `pro_name` joining factors with different levels, coercing to character vector
4: Column `entry_name` joining factors with different levels, coercing to character vector
5: Column `site_name` joining factors with different levels, coercing to character vector
6: Column `pro_name` joining factors with different levels, coercing to character vector
7: Column `entry_name` joining factors with different levels, coercing to character vector
8: Column `site_name` joining factors with different levels, coercing to character vector
9: Column `pro_name` joining factors with different levels, coercing to character vector
10: Column `entry_name` joining factors with different levels, coercing to character vector
11: Column `site_name` joining factors with different levels, coercing to character vector
12: Column `pro_name` joining factors with different levels, coercing to character vector
13: Column `entry_name` joining factors with different levels, coercing to character vector
14: Column `site_name` joining factors with different levels, coercing to character vector
15: Column `pro_name` joining factors with different levels, coercing to character vector

**Comment by jb388** [comment]
fixed ISRaD.extra.delta_delta fx that was source of issue.
