### ISSUE TITLE
ISRaD.extra.fill_soilorders not working properly

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#108]
ISRaD.extra.fill_soilorders function seems to just add the values from pro_soil_taxon, rather than revaluing and categorizing those values. I assume this is because the list is not exhaustive (new templates have been added/the initial list was just for profiles w/ fraction data).

**Comment by greymonroe** [comment]
can you elaborate on what the function is supposed to do?

**Comment by coreylawrence** [comment]
The purpose of this function, written by Christina at the PC meeting, was to convert soil information entered into the original templates (which was not standardized to a single convention) to USDA soil orders (I think...).

**Comment by greymonroe** [comment]
@jb388 I see that you closed issue #123. Does that also mean we can close this issue?

**Comment by jb388** [comment]
Yes, this can be closed.
