### ISSUE TITLE
ISRaD.extra.Cstocks not loading w/ pkg

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#111]
@greymonroe @mguderle 
ISRaD.extra.Cstocks function doesn't load when ISRaD is installed. I checked the NAMESPACE file and noticed that it isn't listed as an "export" object.

**Comment by ShaneStoner** [comment]
Could the spatial soil function could have the same problem then?

**Comment by greymonroe** [comment]
ok should be fixed. for future reference... `#' @export` needs to be in the function header
then you run `devtools::document()` to uipdate the NAMESPACE
