### ISSUE TITLE
Additional controlled vocabulary for "frc_property (f_property)"

### ISSUE THREAD

**Issue by Kate-Heckman** [International-Soil-Radiocarbon-Database/ISRaD#114]
Hi all,

I'm trying to help Susan Crow fine tune one of her templates. I noticed that the controlled vocabulary for frc_property does not have the basic terms required to put input aggregate  or particle size separation data. The controlled vocabulary only includes "silt+clay" but does not include "sand", "macroaggregate" or "microaggregate". Given that frc_property is one of the easiest ways to parse the fraction data, I think it's important to include at least "sand". I know the definitions of "macro" and "micro" aggregate are going to vary, so this point could be debated and folks can alternatively use "frc_scheme" to parse out aggregate data, but we do need "sand" to be included (unless this has already been hotly debated, and I'm missing something).

Thanks!

Kate

**Comment by jb388** [comment]
Hi Kate,
Thanks for sharing this. Personally I feel like the fraction table and associated controlled vocabulary are in need of serious attention (see the other related issues about this, too: #110 #20 #19). Many of the other tables benefited from early attempts at data analysis, followed by subsequent tweaks to the template to improve the usability of the data, but this was not done as much with the fraction table. Let's discuss this on the call tomorrow.

Jeff

**Comment by Kate-Heckman** [comment]
Hi Jeff,


Great! Sounds like a plan.

Thanks!

Kate

**Comment by coreylawrence** [comment]
I also agree that we need to do an update on the Fraction Tab controlled vocabulary. Perhaps Kate and I can take the lead on making some proposed changes - with the input from Olga, Karis, and others who have weighed in. I think we will need to be sure that these changes are associated with a template version update because we will likely want/need to go back through older templates at some point.

**Comment by 1Vicky1** [comment]
I'd like to second Kate's call for a "microaggregate" frc_property. I also need this now to enter fraction data into Doetterl_2018 template. I don't see any alternative of how to call the fraction using the current controlled vocab.

**Comment by jb388** [comment]
Closing this as it is covered in more detail in #147
