### ISSUE TITLE
ISRaD User Manual Fail

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#122]
I am working through the installation tutorial again. I can see one immediate problem. The original code in the tutorial: `devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD", ref="dev", force=TRUE)` 

The current ref setting directs toward the no-longer available dev branch. I assume this should be changed to "master" but could someone please confirm before I make any changes?

**Comment by jb388** [comment]
"dev" branch doesn't exist anymore. You can specify "master" or not specify anything and it will default to master.

**Comment by coreylawrence** [comment]
I made changes to the user manual (as well as other places where this install script shows up) so that copying and pasting of the code line will function correctly (i.e., "dev" -> "master")
