### ISSUE TITLE
issue in delta-delta values in ISRaD_extra

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#126]
Some of these really make no sense based on the other data in the template. I have not been able to figure out where the issue is arising, since the dates, fraction modern & 14c values all look ok. Further exploration is needed to resolve this so we are not serving up faulty calculations in ISRaD_extra.

Examples with problematic values: 
Gaudinski_2001
Sierra_2012
trumbore_inc_unpublished

**Comment by jb388** [comment]
I'll take a stab at this today.

**Comment by jb388** [comment]
@aahoyt Can you explain the exact issue a bit more? I'm still struggling to find anything erroneous in the calculations, but out of context it's hard to see what the problem is. 

If I remember correctly, you were seeing incubation dd14c values that were too low---is that correct?

**Comment by aahoyt** [comment]
The values were all over the place. Just sent you the scripts/plots.

**Comment by aahoyt** [comment]
Reminder - this has never been corrected. We should fix this bug or remove it from ISRaD_extra before submitting the manuscript

**Comment by aahoyt** [comment]
I'll also email an alternative atmospheric record file from Graven et al that Sue suggested to avoid the forward projection issue in SoilR

**Comment by aahoyt** [comment]
I think this was likely due to the date fill issue so I'm closing this issue and starting a more general delta-delta update issue.
