### ISSUE TITLE
R-package "reports" function updates

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#127]
I've made some changes to the `reports` function included in the R-package. Specifically, I added 3 new report options including `report="site_map"`, `report="count_data"`, and `report="frc_data"`.

Additionally, I broke the code for each report option into it's own specific function. I am using the "rep_" prefix to denote sub-functions that can be called with a call to the general "reports" function. This should allow people to easily add new report options as individual functions, which I assume is more useful if the report outputs are then used for other purposes. 

I made `report="count_data"` the default option since it returns the most basic summary of the number of observations at each level of the database. 

The next time you reinstall the database, please play around with these options and feel free to suggest changes here .

**Comment by greymonroe** [comment]
these should be working now.
