### ISSUE TITLE
QA/QC numerical limits on Fraction Modern values

### ISSUE THREAD

**Issue by Kate-Heckman** [International-Soil-Radiocarbon-Database/ISRaD#128]
Would it be possible for the QA/QC to create a warning if the Fraction Modern values are greater than 2? I'm reviewing a template right now, and someone entered percent modern in the fraction modern column and it passed QA/QC. I don't know how difficult it is to add code to the QA/QC, but this addition would be helpful.

Many thanks,

Kate

**Comment by jb388** [comment]
Hi Kate, 
This is an easy addition. I actually thought it was already implemented (the range was 0 to 1.8 for a while). I can look into it.
Jeff

**Comment by Kate-Heckman** [comment]
Hi Jeff,

Thanks! It may already be in there. The template I’m reviewing is from back in May, so the QA/QC was probably updated since then.

Many thanks!

Kate

**Comment by greymonroe** [comment]
The template info file currently does not have a maximum value for frc_fraction_modern (although it has a minimum = 0). We can add a maximum to the info file and the QAQC should update accordingly. We just need to run ISRaD.build to make sure that it doesnt mess anything up before pushing to the repo. 

First, can we confirm that a maximum value is needed for this column? There might be a reason it wasnt there originally that we need to consider.

**Comment by coreylawrence** [comment]
My personal opinion is in line with Kate's request. That is, there is a theoretical maximum value for natural abundance radiocarbon. I think 2 is a reasonable cut-off. If we wanted to be more conservative we could use the maximum value of the atmosphere during the bomb peak (which i don't know off the top of my head). However, I'd guess that is setting things too high. 

Short version, yes we should implement a maximum (for fraction modern and for delta 14C) we just need to decide on what value to use. 

As a side note, we might include a specific error statement for values of the variables falling outside of the set range that reads something like: "The radiocarbon values reported fall outside of the acceptable range for natural abundance measurements, please check your data. If the values you have reported are correct, your data are either from a trace study which cannot be included in this database or your samples may be contaminated. In either case, please contact ISRaD for additional guidance."

**Comment by jb388** [comment]
The reason we didn't implement this initially was because of the possibility of labeled samples. 

Do we want to categorically exclude labeled samples?

**Comment by Kate-Heckman** [comment]
Hi Jeff,

I’m still digging through furlough emails. If you haven’t already resolved this issues, these are my brief thoughts:
I would vote for excluding labeled samples. Besides EBIS, I don’t think there are a lot of relevant soil studies that even use 14C label.

Many thanks,

Kate

**Comment by coreylawrence** [comment]
I also agree on that point. I should probably add a line about that in the manuscript as well...

**Comment by kjmcfarlane** [comment]
Good idea, Corey. I also think the QAQC on the FM is important - I had an old template (one of Elder Paul's papers) that I worked on that had PMC in the FM column.

**Comment by jb388** [comment]
Hi All---thanks for weighing in. I agree with all the sentiments here. I'll implement an upper limit for FM (thinking 1.8), and we should be sure to clarify in our documentation that data from labeled samples will not be ingested.

**Comment by jb388** [comment]
OK, so now I am remembering that we discussed using "Inf" as a proxy for the fm value in studies that reported samples with bomb-14C as "modern". Obviously these records fail QAQC when the upper limit is set to 1.8. 

Unless we can come to consensus for an alternative to reporting "modern" fm values, the limits cannot be impose in QAQC.

**Comment by Kate-Heckman** [comment]
I'm wondering in what way a value of "modern" could be useful? FM values of "modern" can't be included in any statistical test or model unless the whole Fm dataset was reclassified into categorical variables. How many times is data reported as "modern" instead of giving actual numerical values? I would suggest removing any data that isn't reported as a number and imposing the min=0, max=1.8 rule. Just my opinion though...

**Comment by kjmcfarlane** [comment]
A value of "modern" isn't useful, except that it does mean FM >/= 1. I worry "inf" is misleading. Is it a safe assumption that if the values were put in as "modern" there is no quantitative data available to calculate a useful value? (e.g. FM was calculated from a conventional radiocarbon date).

**Comment by Kate-Heckman** [comment]
Cool! Thanks for working through all the devils in the details!

**Comment by jb388** [comment]
Thanks for chiming in, Paul. I think that due diligence on the part of expert reviewers should catch most of these problems. However, it is nice to have the "upstream" check. 

An alternative solution could be a fm_14C_modern column with yes/no options, which would ONLY be used when fm/14C data are reported as "modern".

**Comment by alkalifly** [comment]
Couldn’t we just as easily have the code check to see if the value is > 1.8 OR is Inf?

**Comment by greymonroe** [comment]
Sure, we would just have to write it in the QAQC function. The code is trivial. However, we have discussed such issues in the past and tried to avoid "special cases" like this where the controlled vocab/values deviate from the structure built into the Template Info file. The overall thinking was that this is a slippery slope where our strict rule that the Info file contains all the information needed to know what values to enter in templates no longer is true. When we start putting "asterisks next to" columns, it becomes harder to keep track of whats going on. 

These things being said, we can certainly make whatever changes we decide on to the QAQC. Just need to decide as a group if its important enough. let me know

**Comment by alkalifly** [comment]
In that case, could we not just specify our desired rule (0–1.8 OR Inf) into the info file? This seems less like a "special case" to me than adding a whole new column just to flag values reported as modern. Or can allowed values only be specified within a single continuous range?

At this point, it seems like we have the following options:

1. Change nothing, go on as we have been, and count on expert reviewers to catch any mistakes where people entered percent rather than fraction modern.

2. Implement a check to make sure that values are valid, with valid values being 0–1.8 OR Inf (or something other than 1.8, if preferred)

3. Implement a check for a single continuous range (e.g., 0-1.8) without allowing Inf, but have a separate column that flags samples reported as "modern"

4. Implement a check for a single continuous range and just throw out all of the data reported as "modern"

Personally, from a user perspective, I'm fine with any of the first three options. The only option I am strongly against is 4.

**Comment by jb388** [comment]
My vote would be for option 3. This seems to be the most logical given our overall approach, i.e. adding columns as needed, and keeping the info file consistent.

**Comment by greymonroe** [comment]
yes 3 is what we have been doing

**Comment by alkalifly** [comment]
This is not correct; so far, we have been doing 1, not 3. There ARE currently templates with Inf in the fraction modern column, and we do NOT have any column to flag values reported as modern. If we wanted to adopt option 3, it would require making such a column in the master template, AND going through old templates to convert them to the new protocol.

**Comment by greymonroe** [comment]
Yes sorry, i mean in general, we have added flagging columns in situations like this

**Comment by alkalifly** [comment]
Gotcha. Yes, the extra flag column would definitely be the most consistent with what we already have for other situations. I just want to make sure we know what would have to have to happen to successfully implement it.

**Comment by jb388** [comment]
Currently no upper limit is enforced for FM values by QA/QC, and "Inf" is used for studies reporting FM as "modern".
