### ISSUE TITLE
Entering soil microbial biomass data in the Layer tab

### ISSUE THREAD

**Issue by jcblankin** [International-Soil-Radiocarbon-Database/ISRaD#129]
Soil microbial biomass—as measured by chloroform fumigation extraction (CFE)—is measured on a liquid total organic carbon (TOC) analyzer and is almost never corrected for total soil C. Therefore, the common unit is: ug of microbial biomass-C per g of soil.

It should be relatively easy to convert from ug biomass per g of soil C to per g of soil, assuming that we have %C of soil for every study.
 
“Raw” refers to untransformed microbial biomass C data. These are actual values from the TOC analyzer.
 
“Transformed” refers to microbial biomass data that have been converted from the substrate-induced respiration (SIR) method (usually in units of ug C-CO2 per g of soil per hour) to units of ug microbial-C per g of soil. Effectively this standardizes microbial biomass data from SIR and CFE methods so that they’re in the same units. This transformation uses an equation based on an established (sometimes true) correlation between SIR rates and CFE microbial biomass-C pools. Therefore, chloroform is typically listed as “Raw” in our template, and SIR is listed as “Transformed.”

**Comment by jb388** [comment]
Thanks, Joey. The current version of the template and template info files specifies the units as mg (microbial biomass) C per g (soil), not µg/g. I'm not sure how many templates have microbial biomass data entered, but I would assume (hope) that people converted µg to mg before entering the data. 

Do we want to update the old templates to µg or keep mg?

**Comment by jcblankin** [comment]
Thanks, Jeff.

Most values for microbial biomass should be around 100-400 ug biomass-C per g of soil.

Any MB values around 100-400 mg C g-1 soil just need to be divided by 1000 to convert to ug. These values are 3 orders of magnitude too large—this would mean that soil MB is 10-40% of the weight of soil, which is unrealistic to say the least.

Hope this help!

Joey


---
Joseph Blankinship, PhD
Assistant Professor
Department of Soil, Water & Environmental Science
University of Arizona
529 Shantz Hall, Tucson, AZ 85721
Email: jblankinship@email.arizona.edu<mailto:jblankinship@email.arizona.edu>
Phone: (520) 621-9229

**Comment by jcblankin** [comment]
I just realized that I never really answered your specific question….

Yes, I think the official template should be updated to units of ug biomass-C per g of soil. As far as dealing with all the templates that have already been filled out, I’ll leave it up to you based on what is easiest. If it’s possible to convert units using some sort of script, then great. Basically, any values that are < 1 as listed in the template have probably already been divided by 1000 from units of ug to mg. So these ones just need to be multiplied by 1000. On the other hand, any values > 1 (but ideally in the 100’s) were probably never converted to units of mg, and are therefore already in the correct units of ug.

Cheers,
Joey

---
Joseph Blankinship, PhD
Assistant Professor
Department of Soil, Water & Environmental Science
University of Arizona
529 Shantz Hall, Tucson, AZ 85721
Email: jblankinship@email.arizona.edu<mailto:jblankinship@email.arizona.edu>
Phone: (520) 621-9229


From: Blankinship, Joseph - (jblankinship)
Sent: Wednesday, December 19, 2018 1:24 PM
To: 'International-Soil-Radiocarbon-Database/ISRaD' <reply@reply.github.com>; International-Soil-Radiocarbon-Database/ISRaD <ISRaD@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [International-Soil-Radiocarbon-Database/ISRaD] Entering soil microbial biomass data in the Layer tab (#129)

Thanks, Jeff.

Most values for microbial biomass should be around 100-400 ug biomass-C per g of soil.

Any MB values around 100-400 mg C g-1 soil just need to be divided by 1000 to convert to ug. These values are 3 orders of magnitude too large—this would mean that soil MB is 10-40% of the weight of soil, which is unrealistic to say the least.

Hope this help!

Joey


---
Joseph Blankinship, PhD
Assistant Professor
Department of Soil, Water & Environmental Science
University of Arizona
529 Shantz Hall, Tucson, AZ 85721
Email: jblankinship@email.arizona.edu<mailto:jblankinship@email.arizona.edu>
Phone: (520) 621-9229

**Comment by jb388** [comment]
NB: units were not changed (too much effort); gist of discussion added to template info file by way of clarification.
