### ISSUE TITLE
compile function failing to close connection

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#13]
I updated the package to the latest version, but the compile function is still not working. I can make it through two templates (Angst_unpub, Berg_2004), but then the compiler stops and leaves the connection open. 

**Here's the R console output:**
> scd.mpi2 <- compile("/Users/jeff/R/israd/depthneg/MPI/") # using local directory
ISRaD Compilation Log 

 2018-08-23 22:17:03
 - - - - - - - - - - - - - - - 

Checking compatibility between ISRaD template and info file...Error in gzfile(file, "rb") : all connections are in use

The text output from the Berg_2004 QAQC log (last one before the crash) had the same error.

**Comment by jb388** [comment]
@greymonroe: Seems like this is a similar problem to before, where the failure to pass QAQC leaves the connection open. I fixed the name issues in the first three templates, but then the 4th one (Certini_2003) left the connection open and the compile stopped. Apparently certain errors just trigger this, because all of the templates are still failing, but not all of them stop the compiler.

**Comment by ktoddbrown** [comment]
Can I suggest specifying a write file instead of setting sink?

**Comment by greymonroe** [comment]
Good call, no longer using sink. Should be functioning better now.
