### ISSUE TITLE
remove data objects from R package and add necessary download functions

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#137]
The objects in /data are to be removed. This requires:

1. Remove /data objects
2. Add column to template and info file that notes the ISRaD version
3. Add function that downloads data objects from github and tells user which version it is
4. update build function so that it saves data objects to database/ folder where they will be available for download
5. remove documentation for data objects from man/
6. add feature to build function to update version number. 
7. add function that extracts version number from ISRaD data object

**Comment by greymonroe** [comment]
I just added a function to address this. ISRaD.download now downloads the data files from github to a local directory.

**Comment by jb388** [comment]
Great! Thanks for doing this, Grey.

**Comment by greymonroe** [comment]
done. see vignette here https://international-soil-radiocarbon-database.github.io/ISRaD/rpackage/

still need to delete the old files but I want to make sure everyone is ok with that
