### ISSUE TITLE
Remove files from ISRaD_data_files_in_progress

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#138]
ISRaD_data_files_in_progress currently contains templates that have been superseded by completed/corrected templates now in ISRaD_data_files. These template files should be removed from ISRaD_data_files_in_progress in the next update. 

Also, if you have completed any templates from ISRaD_data_files_in_progress, please check to see whether the superseded template has been deleted. If it hasn't, please list it here so it can be flagged for removal.

Templates to remove:
- [ ] Gaudinski_2000_fromHeSynthesis.xlsx
- [ ] Gaudinski_2000.xlsx
- [ ] Tegen_1996.xlsx

**Comment by mguderle** [comment]
I checked the folder ISRaD_data_files_in_progress and removed the following files, which were already updated during the last months:

- Caner_2001
- Dumig_2008
- Gaudinski_2000
- Li_2010
- Paul_1997
- Resh_2002
- Scharpenseel_1973a
- Sollins_2006
- Tegen_1996 
- Torn_1997
- Trumbore_1995_OK
- Trumbore_1995_fromHeSynthesis
