### ISSUE TITLE
CRAN check failing

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#139]
These files are causing CRAN checks to fail. I will be commenting out their content until they are fixed.

ISRaD.extra.geospatial.soil
rep_count_data
rep_frc_data
rep_site_map

The issue is caused by "no visible binding for global variable" warnings, which basically means that objects or functions are being called which have not been created yet or which the source package is not specified.

**Comment by coreylawrence** [comment]
@greymonroe 
Is this related to piping in dplyr (ie., not using ".data" to illustrate the variable passed to a second order process within the piping? Or is it something else?

**Comment by greymonroe** [comment]
Yes this is one of the issues

**Comment by greymonroe** [comment]
rep_count_data
rep_frc_data
rep_site_map

are now cleared for CRAN checks and have been uncommented
