### ISSUE TITLE
More updates needed to Template Info file

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#14]
I noticed there are a few more errors in the template info file that need to be fixed, e.g. site elevation range should be from -413 to 8900, latitude range should be from -90 to 90, not -180 to 180, etc.

I will go over the template info file and make a pull request once I have reviewed it.

**Comment by greymonroe** [comment]
If blank values are acceptable, it should not be required.

**Comment by jb388** [comment]
Master Template/Template Info file status: I updated many of the acceptable value ranges as well as some controlled vocabulary for the non-required fields in the template info file. I also updated all of the observation date columns in both the Master Template and the Template Info files from a singular date field to three numeric fields (yyyy, mm, dd). I changed the value in the "Required" field of the Template Info file to "Yes" for the year columns in the flux, layer, and interstitial tables, but set the value to "No" for all other observation date columns. 

I am currently in the process of updating the MPI and Powell Center templates accordingly. @greymonroe : can you incorporate this change when you convert Yujie's templates to the new Master Template format?

**Comment by greymonroe** [comment]
All of this sounds good. But there is only one template for ISRaD (not divided between MPI and Powell Center).

**Comment by greymonroe** [comment]
"or blank" should not be included in the controlled vocab

**Comment by jb388** [comment]
Yes, I know there's only one Master Template---I meant the entries completed by the respective groups.

**Comment by jb388** [comment]
Thanks for clarifying the "or blank" syntax.

**Comment by greymonroe** [comment]
> Yes, I know there's only one Master Template---I meant the entries completed by the respective groups.
Ah ok sounds great.

**Comment by jb388** [comment]
Up-to-date Master Template and Template Info files uploaded. See pull request.

**Comment by greymonroe** [comment]
ok, i accepted the pull request and will go ahead and close this issue
