### ISSUE TITLE
Social media presence

### ISSUE THREAD

**Issue by ShaneStoner** [International-Soil-Radiocarbon-Database/ISRaD#141]
We launched an [ISRaD twitter account](https://twitter.com/soilradiocarbon)!

The email account associated is info.israd@gmail, with the standard password. I encourage anyone to contribute. These tweets are also via a twitter widget that is visible on the ISRaD about and landing pages. 

Updates on added datasets, new publications, conferences, collaborations, and added functions would all be good contributions. Plus, we should follow those involved in this project and promote related work.

**Comment by ShaneStoner** [comment]
Hey everyone,
I think we really need some sort of logo, for the website and for talks, coffee mugs, you name it.

Here are a couple few I came up with this morning. Let me know your thoughts, favorites, or if you have  ideas too. If they all stink, let me know that too! 

1.
<img width="879" alt="screen shot 2019-01-17 at 11 53 14" src="https://user-images.githubusercontent.com/37864035/51345557-332ffe80-1a50-11e9-9174-4461b0205448.png">

2.
<img width="910" alt="screen shot 2019-01-17 at 11 53 29" src="https://user-images.githubusercontent.com/37864035/51345604-5195fa00-1a50-11e9-827a-e8b4f584ade1.png">

3.
<img width="927" alt="screen shot 2019-01-17 at 11 53 42" src="https://user-images.githubusercontent.com/37864035/51345622-578bdb00-1a50-11e9-9232-6cb2fb3fa085.png">

4. 
<img width="884" alt="screen shot 2019-01-17 at 11 53 56" src="https://user-images.githubusercontent.com/37864035/51345634-5d81bc00-1a50-11e9-8ec3-9e8e743e27bb.png">

5. 
<img width="887" alt="screen shot 2019-01-17 at 11 54 08" src="https://user-images.githubusercontent.com/37864035/51345648-66728d80-1a50-11e9-8625-f19e4cf3f5af.png">

6. 
<img width="840" alt="screen shot 2019-01-17 at 11 54 36" src="https://user-images.githubusercontent.com/37864035/51345674-725e4f80-1a50-11e9-81e6-89fef2533448.png">

7. 
<img width="769" alt="screen shot 2019-01-17 at 11 55 16" src="https://user-images.githubusercontent.com/37864035/51345696-77bb9a00-1a50-11e9-972a-bfb517f35920.png">

8. 
<img width="953" alt="screen shot 2019-01-17 at 11 59 41" src="https://user-images.githubusercontent.com/37864035/51345709-7ee2a800-1a50-11e9-90b9-5acef7582ace.png">

9.
<img width="903" alt="screen shot 2019-01-17 at 12 00 25" src="https://user-images.githubusercontent.com/37864035/51345719-843ff280-1a50-11e9-97c0-6d3f2b653a17.png">

10. 
<img width="1024" alt="screen shot 2019-01-17 at 12 00 44" src="https://user-images.githubusercontent.com/37864035/51345727-899d3d00-1a50-11e9-9faa-c6023748754c.png">

**Comment by 1Vicky1** [comment]
Awesome job, Shane! You are right, logo is needed! I think I like number 1 (where bomb curve does not invade the full name) and 7 the best. In any cases I would put a slightly larger gap between the abbreviated and full name. Also in case of 1, I would also try what a little thicker bomb curve would look like.

**Comment by ShaneStoner** [comment]
Alison, Paul and Sue helped come up with a few slight tweaks:

11.
<img width="1086" alt="screen shot 2019-01-17 at 14 06 43" src="https://user-images.githubusercontent.com/37864035/51352039-51eac100-1a61-11e9-9c2f-f7cac3a9cbc9.png">

12.
<img width="938" alt="screen shot 2019-01-17 at 14 07 21" src="https://user-images.githubusercontent.com/37864035/51352062-6202a080-1a61-11e9-898a-441eb046cf53.png">

13.
<img width="1024" alt="screen shot 2019-01-17 at 14 06 54" src="https://user-images.githubusercontent.com/37864035/51352074-67f88180-1a61-11e9-87e6-312cdea329e8.png">

**Comment by ShaneStoner** [comment]
Here's the ppt that I used to make these, if anyone wants to make edits

[ISRaDLogos.pptx](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/2771174/ISRaDLogos.pptx)

**Comment by greymonroe** [comment]
i like 11 and 13

**Comment by coreylawrence** [comment]
Here are two more options that eliminate the overlapping of the bombspike and text (but create additional dead space). 
[ISRaD.pdf](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/2780330/ISRaD.pdf)

[ISRaDv3.pdf](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/2780331/ISRaDv3.pdf)

**Comment by kjmcfarlane** [comment]
These are awesome! I like 13 the best.

**Comment by ShaneStoner** [comment]
Hey Corey, I really like #15! Definitely cleaner. My only thought is about how the delta isn't _exactly_ between the R and D, but that's probably just me.

**Comment by Kate-Heckman** [comment]
I vote for #12

**Comment by greymonroe** [comment]
looks like a decision has been made. nice work @ShaneStoner!
