### ISSUE TITLE
Split build fx into two fxs

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#152]
Currently the build function performs two main tasks: 
1) Compile the database from the template directory (and QA/QC, etc.)
2) Run CRAN checks on the codebase

@greymonroe @mguderle 
It seems like it would be beneficial to provide the second functionality (CRAN checks on codebase) for general users interested in contributing code. However, we wouldn't want these users to push a new version of the database itself to github, as they may not have all the up-to-date templates, or have non-approved templates in their directory.

**Comment by greymonroe** [comment]
In essence the build function is just a combination of those two functions.
1) compile()
2)devtools::check()

users who arent pushing to CRAN can still run either of those independently.

**Comment by jb388** [comment]
Good to know. OK, perhaps it would be good add this to the FAQ to let potential code contributors know that they can run the devtools::check() fx to make sure their code passes the CRAN checks.
