### ISSUE TITLE
Expert Review Standardization and Management

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#154]
**(1)**We should standardize the expert review process as much as possible. With that in mind, I have created a google webform (and transferred ownership of said form to info.israd): [Expert Review Form](https://docs.google.com/forms/d/10qoBknzTYRT1MJk9OyCpDSIGnDFqbKE1O6iQmF1jCjQ/edit?usp=sharing). Please have a look and edit as you see fit. At the moment anyone accessing the webform with the above link can change or add questions. 

The idea is that reviewers step through each section as needed and address a few  standard questions. At the moment the questions are general but I think it would be good to add some more specific questions that come up regularly for each level of the template being reviewed. I'd like to keep this relatively easy so we don't need to include every possible question we can think of - maybe just those common issues that expert reviewers should be on the lookout for.

For example, with regard to the site level - I included an question: Do the coordinates plot correctly? This is a common process I take when reviewing: copy one set of coordinates from template, paste into google maps, does the resulting location roughly correspond with the site reported in the paper/template? 

**(2)**With regard to template submission  as it pertains to the expert review. I think we should request that original data being entered (i.e., the .pdf file of the publication) be included by the curator in their submission to info.isard **AND** by the editor in their request for expert review. Most importantly, I don't think the expert review can be completed effectively without checking the template against the original source data. And I don't think we should have to ask the reviewers to find the source data. This may be a minor issue for most people but for others without journal access or for obscure data sources, it creates a problem that limits the effectiveness of the review.  I am personally having this issue now, because of the furlough I am locked out of my access to journal subscriptions.

**Comment by jb388** [comment]
@coreylawrence 
I agree that we should standardize the expert review process, and this seems like a reasonable way to achieve that. Thanks for pulling it together. 

I am a little wary of generating more "paperwork", but on the other hand I see the value in having some sort of meta record of the review process (apart from the original submitted template and the accepted template). So I'd say let's try working with this new form for a while and reevaluate as necessary.

I am 100% behind the requirement to attach the source data (whether pdf of published paper or spreadsheet with ancillary data). I think this has been brought up before, and we should make sure that this requirement is documented in the FAQ/website guides.

**Comment by ShaneStoner** [comment]
I think we definitely need to create a paper trail of the process, especially if any changes are made (I'm thinking simple changes that could be done by the reviewer instead of being sent back to the submitter). I like the google form: it's easy to fill out and I don't think it would add too much time to the reviewing process, and may end up saving a ton of time in the future. I will add questions as I go along.

Agreed on the "attaching source data" policy. It will also help identify both larger discrepancies vs. human error.
