### ISSUE TITLE
What version/build of Excel was used for creating ISRaD_Template_Info.xlsx file?

### ISSUE THREAD

**Issue by AuHau** [International-Soil-Radiocarbon-Database/ISRaD#158]
As I worked on #156 I bumped on a problem of parsing the file ISRaD_Template_Info.xlsx with the tool I choose, because of some inconsistent metadata. I submitted an Issue to the authors of the tool (see: https://github.com/SheetJS/js-xlsx/issues/1412), they analyzed the file and was interested to find out what sort of version of Excel (most likely?) created the file. It would be nice to provide them the information as you will have their tool on yours website.

Please see the issue for more details.

**Comment by greymonroe** [comment]
version 16 i think. not sure the minor version
