### ISSUE TITLE
Handling carbonate removal

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#16]
To discuss/standardize: How do we want to enter bulk data where carbonates were removed? Should this be entered on profile tab since it is a standard treatment? Or do we want to be more technically correct (and more confusing) and enter it on the fractions tab? (it's also listed there). Relatedly, what is the fraction cutoff value (frc_lower & frc_upper) supposed to be if the scheme_units are presence/absence? 
Examples: Czimczik & Welker, 2010

**Comment by jb388** [comment]
Just to chime in: I instructed the students to enter carbonate removal at the layer level (not as a fraction), so all of the MPI templates should follow this convention. I thought we had discussed this at some point in the past, but perhaps not?

**Comment by coreylawrence** [comment]
Bulk carbonate data is entered in the layer tab, unless there is radiocarbon data. In that case, it is likely repeated in the fraction tab including the 14C values. I see the point about why it should be included in the fraction tab but you could also extend the same argument to include organic carbon. So we are in a bit of gray zone but I think the convention we have been using makes the most sense.

**Comment by greymonroe** [comment]
What is the final decision on this?
