### ISSUE TITLE
Page for ISRaD news & technical updates

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#160]
As discussed at UCI, I made one here to complement the twitter feed!
https://international-soil-radiocarbon-database.github.io/ISRaD/news/

It is linked from the homepage. Feel free to add content - hopefully a useful place for people to check in who want to catch up with major technical or procedural changes within the project.

**Comment by ShaneStoner** [comment]
Hey Alison! Great work. I am glad we have this. I went ahead and placed it above the twitter feed. I don't want it to get missed!

**Comment by greymonroe** [comment]
Should we update with the new paper and release? We might want to make some formal decision about who/when to update this page otherwise I think it will get forgotten.
