### ISSUE TITLE
Dev status

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#163]
Just a reminder about "dev" vs. master:
1) Never work directly on the master branch
2) Make a new "dev" branch when you want to develop some new code or implement changes (each one of us could have multiple dev branches). Once you finish what you are working on you should run "build" or some combination of QAQC, checkTempletFiles, and devtools::check to make sure your code doesn't break anything. Finally, submit a pull request to merge your branch back with master. 
3) Ideally a "dev" branch will have a short lifespan, as that limits the chances for merge conflicts!

**Comment by jb388** [comment]
Also, anyone who has more insight into good development practice, feel free to chime in!

**Comment by greymonroe** [comment]
naming scheme?

"DEV-user-description"

**Comment by jb388** [comment]
@greymonroe  Sure, that sounds good.

**Comment by jb388** [comment]
In case this process confuses anyone, here's a nice tutorial that explains the process: 
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

**Comment by jb388** [comment]
Closing this, as it was an FYI post to begin with.
