### ISSUE TITLE
installation - request to update packages 

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#172]
Just fyi I get this prompt when installing the updated version. I assume it's not a problem, but let me know if so.

> install_github('International-Soil-Radiocarbon-Database/ISRaD', ref = "master", force = T)
Downloading GitHub repo International-Soil-Radiocarbon-Database/ISRaD@master
These packages have more recent versions available.
Which would you like to update?

 1:   BH           (1.66.0-1    -> 1.69.0-1   ) [CRAN]   2:   callr        (3.0.0       -> 3.1.1      ) [CRAN]
 3:   clipr        (0.4.1       -> 0.5.0      ) [CRAN]   4:   colorspace   (1.3-2       -> 1.4-0      ) [CRAN]
 5:   crul         (0.6.0       -> 0.7.0      ) [CRAN]   6:   curl         (3.2         -> 3.3        ) [CRAN]
 7:   dbplyr       (1.2.2       -> 1.3.0      ) [CRAN]   8:   dplyr        (0.7.8       -> 0.8.0.1    ) [CRAN]
 9:   evaluate     (0.12        -> 0.13       ) [CRAN]  10:   forcats      (0.3.0       -> 0.4.0      ) [CRAN]
11:   forecast     (8.4         -> 8.5        ) [CRAN]  12:   ggmap        (2.6.1       -> 3.0.0      ) [CRAN]
13:   git2r        (0.23.0      -> 0.24.0     ) [CRAN]  14:   haven        (1.1.2       -> 2.1.0      ) [CRAN]
15:   httpuv       (1.4.5       -> 1.4.5.1    ) [CRAN]  16:   httr         (1.3.1       -> 1.4.0      ) [CRAN]
17:   jsonlite     (1.5         -> 1.6        ) [CRAN]  18:   knitr        (1.20        -> 1.21       ) [CRAN]
19:   later        (0.7.5       -> 0.8.0      ) [CRAN]  20:   markdown     (0.8         -> 0.9        ) [CRAN]
21:   modelr       (0.1.2       -> 0.1.4      ) [CRAN]  22:   openssl      (1.1         -> 1.2.1      ) [CRAN]
23:   processx     (3.2.0       -> 3.2.1      ) [CRAN]  24:   ps           (1.2.1       -> 1.3.0      ) [CRAN]
25:   purrr        (0.2.5       -> 0.3.0      ) [CRAN]  26:   R6           (2.3.0       -> 2.4.0      ) [CRAN]
27:   raster       (2.8-4       -> 2.8-19     ) [CRAN]  28:   RcppArmad... (0.9.200.4.0 -> 0.9.200.7.0) [CRAN]
29:   rcrossref    (0.8.4       -> 0.9.0      ) [CRAN]  30:   readr        (1.1.1       -> 1.3.1      ) [CRAN]
31:   readxl       (1.1.0       -> 1.3.0      ) [CRAN]  32:   rmarkdown    (1.10        -> 1.11       ) [CRAN]
33:   rstudioapi   (0.8         -> 0.9.0      ) [CRAN]  34:   stringi      (1.2.4       -> 1.3.1      ) [CRAN]
35:   stringr      (1.3.1       -> 1.4.0      ) [CRAN]  36:   tibble       (1.4.2       -> 2.0.1      ) [CRAN]
37:   tinytex      (0.9         -> 0.10       ) [CRAN]  38:   tseries      (0.10-45     -> 0.10-46    ) [CRAN]
39:   urltools     (1.7.1       -> 1.7.2      ) [CRAN]  40:   xfun         (0.4         -> 0.5        ) [CRAN]
41:   CRAN packages only                                42:   All                                             
43:   None                                              
Enter one or more numbers separated by spaces, or an empty line to cancel

**Comment by greymonroe** [comment]
This is ok, it just means that the packages have more recent versions on CRAN. I get these messages often and just update all. There are so many because we call a lot of packages in our different functions. This list includes those packages and their dependancies.

**Comment by aahoyt** [comment]
ok good!
