### ISSUE TITLE
DOI for submission

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#174]
Starting this thread to discuss the database DOI for submission. Where are we planning to submit this to get a DOI?

**Comment by jb388** [comment]
I can go ahead and get the DOI whenever---just planning to go through Zenodo. However, I suppose I would then be the contributing author for that, so if you would prefer to do it, Corey, that's fine. 

We had discussed waiting until a few more of the Treat synthesis entries were complete, but also discussed just going ahead with the DOI anyway. I can't remember what we decided. 

Can @aahoyt and @greymonroe weigh in on waiting/not waiting for the Treat synthesis?

**Comment by aahoyt** [comment]
Jeff & I discussed today - we decided we should go ahead on the DOI without waiting for the Treat datasets, since it would be good to spend a bit more time manually quality controlling them, rather than rushing through. 

Corey, feel free to go for it! Otherwise we'll do it at MPI tomorrow (Mar 5th)

**Comment by greymonroe** [comment]
I agree that curating the Treat datasets is a good idea. We can add them before resubmission in the future.

**Comment by alkalifly** [comment]
For whatever it’s worth, I am in the midst of finally getting all of the USGSOF templates finished up. I should be done by tomorrow, if there is any thought that it might be worth waiting another day to have those in

**Comment by greymonroe** [comment]
@alkalifly sounds great, are these ready now?

**Comment by alkalifly** [comment]
> @alkalifly sounds great, are these ready now?

@greymonroe I'm still sorting out some issues with these, trying to get them in as soon as possible, but don't wait on it for the DOI

**Comment by coreylawrence** [comment]
We are still waiting for the USGS Bureau approval of the manuscript so I am holding off on issuing a DOI until that is done. Should be any day now but there is still a little bit of time to add additional datasets.

**Comment by coreylawrence** [comment]
Hi Folks,

Update: The manuscript has received the necessary approval and can now be submitted. I've made one final round of editorial revisions based on 3 additional sets of author comments so I think we are there. The last step is to issue a new release of the repository and to register a dataset DOI. I have a couple questions first:

(1) Are we at an ok point with various ongoing efforts to ingest data and build/fix infrastructure to issue a release? I'd like to get this thing submitted ASAP but I want to be sure we are at a good place for a version release.

(2) Should we issue a release that is v1.0 now or continue with lower numbering (current release is 0.6), perhaps until the paper is accepted?

Please weigh in promptly if you have thoughts either of these two issues.  
@jb388 @aahoyt @greymonroe @crlsierra @alkalifly

**Comment by aahoyt** [comment]
That's great!

(1) Yes, I think we are good to go! Data is always being added, but I think we're at a good point so you should go ahead with the DOI. Infrastructure is also stable enough. We are still in progress with the Treat synthesis, because we keep running into additional issues, so it won't be included. But I think that's totally fine and we plan to finish before the accepted version

(2) I don't have much preference on this. Perhaps make the accepted paper release 1.0? So this release would still be lower. I'm fine with whatever you decide.

**Comment by alkalifly** [comment]
Congratulations, Corey, on this tremendous effort. For your point 1, I had a chance to get everything added/fixed, so it's goodto go on my end. For point 2, I can see how it's a bit of a chicken or egg conundrum, but I tend to think that it doesn't really matter, and either way would be fine. From an end user perspective, the existence of a DOI that I can cite is the important thing; the actual version number is inconsequential.

**Comment by jb388** [comment]
@coreylawrence Great news! Thanks again for all your hard work on this, excited to see it get out there. Nothing substantial to add to the above comments---I also feel good about where we are with infrastructure, and I don't have a strong opinion on the release number, but if pressed I would echo Paul and make the accepted release v1.0.

**Comment by crlsierra** [comment]
I think we can go with version 1.0. This will be the first official release associated with the first public version of the paper. Once it gets accepted, we can increase the counter if major changes are done.

**Comment by coreylawrence** [comment]
Ok. Thank you all for your input. We will go with the version 1.0 release now. I sent off an separate email to Grey to make sure I get the release process right but I haven't heard back so I may just give it a try.

**Comment by coreylawrence** [comment]
v1.0 is released with the corresponding datasets loaded at Zenodo:
https://doi.org/10.5281/zenodo.2613911
