### ISSUE TITLE
Depth convention inconsistencies

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#176]
I have been noticing a number of profiles with organic horizons that have a positive depth. If I've understood the decisions in #2 correctly, then I believe these layers should have negative depths. See, for example, Dümig_2008, Gentsch_2018, and O'Donnell_2011.

Going forward, we should definitely make sure that the expert review considers this. I'm not sure what to do about the existing entries, aside from checking them all one by one and fixing them manually.

**Comment by jb388** [comment]
FYI I pushed an updated version of Dümig_2008 to git just now.

**Comment by alkalifly** [comment]
Thanks @jb388 for fixing Düming_2008.

I'm still a little confused about Gentsch_2018; I see that the lyr_all_org_neg is entered as yes, but many of lyr_hzn entries look like A, B, and C horizons, which suggests mineral soil to me, but perhaps I am just not understanding the nomenclature.

I'm even more confused by O'Donnell_2011, which seems to comprise only a single profile, and has both organic and mineral layers that seem to overlap in depth, all of which are entered as positive depths, but not all of which are below the organic-mineral interface.

**Comment by jb388** [comment]
@alkalifly The Gentsch data was very confusing as it was all from permafrost sites with varied active layer depths. For example, the "Ajj" horizons have descriptions like, "less decomposed material", which to me indicates an organic horizon. I think accurate depth reporting is an endemic problem for permafrost sites, and I'm not sure how best to represent them.

**Comment by alkalifly** [comment]
@jb388 Okay, it turned out there was some confusing stuff going on with O'Donnell, but Kate and I worked everything out.
