### ISSUE TITLE
ISRaD_extra_list.xlsx problem with Inf numerical values

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#178]
Something is happening when the ISRaD_extra_list.xlsx gets written where all values of Inf or -Inf end up as #NUM! See, for example, the lyr_bot entry for Biedenbender_2004, Walnut Gulch, walnut center, walnut_center_186_+.

The non-extra ISRaD_list.xlsx file is fine, and the ISRaD_extra_flat_xxx.csv files are also fine, so it is something specific in the writing of extra Excel file.

**Comment by jb388** [comment]
Nice sleuthing, @alkalifly I don't believe Excel has a way of recording infinite values: [see](https://stackoverflow.com/questions/33145404/is-there-infinity-in-spreadsheets). Sounds like we will have to decide on an infinity proxy value, e.g. 1e99. Replacing Inf values with the proxy will have to be done before the excel file is output.

**Comment by greymonroe** [comment]
Another possible solution is to convert everything to character data types before saving which will convert Inf to "Inf" and should save it in the excel file accordingly. Then when R reads the excel file it inteprets "Inf" as Inf automatically so it should be seamless. I will work on implementing and testing.

**Comment by alkalifly** [comment]
The solution that @greymonroe seems like a good one because the ISRaD_list.xlsx file (non-extra) is already all in character data, which is why it doesn't have this problem. Making ISRaD_extra_list.xlsx also be character data would keep everything consistent. Also, @greymonroe while you are working on this, if it is an easy enough thing to do, it might be good to have ISRaD_extra_list.xlsx file have the same full three-row header (with description and units) as the ISRaD_list.xlsx file does. Currently it only includes the top row, so row numbers are not consistent between the two files (i.e., row 4 in ISRaD_list.xlsx is the same entry as row 2 of ISRaD_estra_list.xlsx)

**Comment by greymonroe** [comment]
fixed in recent updates
