### ISSUE TITLE
R object from "compile" function is null

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#18]
The compile function runs the QAQC function and generates useful files in the "database" folder of the specified directory. This is great! But it does not generate an R object.

In the old package we had "compileAsList" to return a list, and the function "compile" returned the flat database. Could we have this be an option in the function?

Perhaps we can discuss more next week as we dig into data structure and data management some more.

**Comment by greymonroe** [comment]
K, should be addressed with last commit. compile() should now return the database in list or flat structure depending on how the **return** parameter is set in the compile() function, either "list" or "flat" while default is NULL which returns nothing but still completes the compilation and saves appropriate files. 

Example:
```
compiled<-compile(dataset_directory = "~/Desktop/Data/", write_report = T, write_out = T, return="flat")
```

**Comment by greymonroe** [comment]
Thanks, can you try again?

**Comment by aahoyt** [comment]
Now the function will run but produces a NULL list after the following error for me:
...
Joining, by = c("entry_name", "site_name")
Joining, by = c("entry_name", "site_name", "plot_name", "pro_name")
Joining, by = c("entry_name", "site_name", "pro_name")
Joining, by = c("entry_name", "site_name", "pro_name")
Joining, by = c("entry_name", "site_name", "pro_name", "lyr_name")
Joining, by = c("entry_name", "site_name", "pro_name", "lyr_name", "lyr_comp", "frc_name")
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'C:/Users/Alison/Dropbox/TestCompilation/Updated30-08-2018/database/ISRaD_flat.csv': Permission denied

**Comment by aahoyt** [comment]
Yes, now it works! Thanks!

**Comment by greymonroe** [comment]
Ok cool, yeah that shouldn’t normally be a problem though. Do you know if you currently had the csv file open when you ran the compile function?

**Comment by aahoyt** [comment]
ok yes, just double checked and I think that was the issue - oops!

**Comment by greymonroe** [comment]
No worries, perhaps there is a workaround so this isnt an issue, or at least generates a message that is useful to the user.
