### ISSUE TITLE
Added PET functionality to ISRaD.extra.geospatial.climate.R

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#180]
Multiple people have requested that PET be added to the ISRaD extra object. This has been done. PET data come from Kramer and Chadwick 2018 (climate input is from Worldclim, Penman-Monteith method for short-clipped grass was used in PET calculation).

Note that running build now requires an extra directory argument: geodata_pet_directory (as do the functions ISRaD.extra.geospatial.climate and ISRaD.extra). The actual PET data has been added to the Keeper folder, so to run the functions set the directory path to, e.g. "~/Seafile/ISRaD_keeper/ISRaD_extra_spatialdata/pet".

@aahoyt

**Comment by aahoyt** [comment]
Awesome!!

**Comment by greymonroe** [comment]
Seems ok to close
