### ISSUE TITLE
Database structure on website not showing

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#182]
The link for showing the database structure (on the website) isn't working. Cool idea, tho.

**Comment by AuHau** [comment]
Hmm, this is related to #158, not sure how this issue get reintroduced. I have submitted PR with a corrected version of the template.

In future when this happens you can run this script to have it corrected. You have to run in in the folder where `ISRaD_Master_Template.xlsx` is placed.

```sh
$ unzip -d out ISRaD_Template_Info.xlsx
$ grep -rl '<color indexed="206"/>' out/ | xargs sed -i "" 's/<color indexed="206"\/>//g'
$ cd out
$ zip ISRaD_Template_Info.xlsx -r *
$ mv ISRaD_Template_Info.xlsx ..
$ cd ..
$ rm -rf out
```

**Comment by AuHau** [comment]
Btw. in future if it is not working, first on the database template viewer validate in console (eq. right click in tha page and "Inspect") that you get this error:
```
Uncaught Error: <color indexed="206"/>
    at xlsx.full.min.js:17
    at Array.forEach (<anonymous>)
    at go (xlsx.full.min.js:17)
    at i (xlsx.full.min.js:17)
    at vp (xlsx.full.min.js:20)
    at fg (xlsx.full.min.js:23)
    at ug (xlsx.full.min.js:23)
    at Object.bg [as read] (xlsx.full.min.js:24)
    at XMLHttpRequest.req.onload ((index):217)
```

If so then run the script and it should fix it. If not create an issue and mention me and I will have a look.
