### ISSUE TITLE
usefulness of pro_comp column not clear (?)

### ISSUE THREAD

**Issue by 1Vicky1** [International-Soil-Radiocarbon-Database/ISRaD#184]
Yesterday me and Alison were discussing some templates and became unsure about the usefulness of the **pro_comp** column (Are profile data from composite sample?), i.e. its added value to **lyr_comp** column (Are layer data from composite?).
Can someone think of a case where a profile and respective layer data would be flagged "yes" in one of these columns but not in the other one and this would bring any extra information about the study design?
Me and Alison thought that pro_comp column may be redundant because if there is any combining of samples into a composite sample, this will be already indicated by a flag in the lyr_comp column.

**Comment by jb388** [comment]
I suppose there could be situations in which some layers of multiple profile have been composited, but not the entire profile. This seems like it would not be a common scenario. But at this point I think we may as well leave the field in the template.
