### ISSUE TITLE
Generating elevation based on coordinates: in data entry or using israd.extra?

### ISSUE THREAD

**Issue by 1Vicky1** [International-Soil-Radiocarbon-Database/ISRaD#185]
When looking through some templates and also some feedback that reviewers gave in the Expert Review Form I noticed that sometimes people extract elevation from Google Maps using the coordinates. I personally haven´t been doing that (if elevation is not reported in the paper, I don´t fill it in). I think that a more transparent way round would be to have an israd.extra function for that and keep only reported elevations in the templates. What do you think?

**Comment by alkalifly** [comment]
I concur; it seems misleading to include elevations that were not explicitly reported unless it is part of an israd.extra function. If the coordinates are not reported with a high degree of precision and the general area has a lot of topographic variability, a google-extracted elevation could be very different from the actual elevation of the profile. The only problem is all of the existing templates where this has already been done, and would require manual identification and correction.

**Comment by greymonroe** [comment]
I agree that filling templates with elevation data only when presented in the paper is the best way to go. Theres no way to fix old templates but as a general rule I agree that leaving blank and filling with israd.extra functions is more transparent and reproducible.
