### ISSUE TITLE
Lat/Lon error

### ISSUE THREAD

**Issue by kjmcfarlane** [International-Soil-Radiocarbon-Database/ISRaD#186]
Nagy_2017 has longitude values entered with the wrong sign (should be negative--western hemisphere). (I think this is the right place to submit this problem)

**Comment by kjmcfarlane** [comment]
It also has data in the lyr_14c_sd column that doesn't make sense (it's almost the Delta value, obviously not an SD).

**Comment by alkalifly** [comment]
This was fixed in 2febc76ba6dfa35d90664b8ab7688423eff466d1, so your version must be out of date. Make sure you pull the latest from Github.

**Comment by kjmcfarlane** [comment]
I thought I did, but I must not have! Thanks!
