### ISSUE TITLE
2D position called SEEPLINE (Khomo_2017 template)

### ISSUE THREAD

**Issue by agathadrk** [International-Soil-Radiocarbon-Database/ISRaD#187]
Hi! Does anybody know how would I classify a 2D position called SEEPLINE? The entry names available are (summit, shoulder, backslope, footslope, interfluve) or is it different from those listed?

**Comment by jb388** [comment]
My understanding is that a seepline forms when ground water meets an impervious layer in the soil, causing it to "seep" out at the surface. For this process to occur I believe it must be on a slope of some sort, so my best guess would be "footslope". Alternatively, you can just leave the field blank.
