### ISSUE TITLE
Package to CRAN

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#190]
@greymonroe @aahoyt @coreylawrence @crlsierra @alkalifly @ShaneStoner 
To do:
- remove data from package (seems to still be there as of 13 June 2019)
- anything else?

**Comment by jb388** [comment]
Forget that first comment...data is now gone (had old install of package still there with the data).
More specifically, has the updated package been sent to CRAN?

**Comment by jb388** [comment]
Sorry for the spam on this issue, but the data, in fact, IS still included in the package right now.

So, I think once it's been pulled, we should be able to submit to CRAN, right?

**Comment by greymonroe** [comment]
Yeah it should be ready for cran. I am submitting it this weekend

**Comment by greymonroe** [comment]
also there is the graven.rda object in the data folder. Sorry if im just forgetting but when did this get added?  Cant seem to recall the history of this file

**Comment by jb388** [comment]
I think you added that file. Since that file shouldn't change with any frequency, I think it's fine to keep that in the package.

**Comment by greymonroe** [comment]
Haha ok that’s what I thought but when I looked at commit history it seemed to show it was only 2 days old

**Comment by jb388** [comment]
Yeah, when I changed the name I had to replace the object.

**Comment by greymonroe** [comment]
https://builder.r-hub.io/status/ISRaD_0.1.1.tar.gz-33874d571ec84bd1a505ee2a82956b2e

We may be having some issues sending to CRAN. I think we have too many package dependencies

**Comment by jb388** [comment]
Hmm, thanks for checking this, @greymonroe 

These are the errors I found in the builder output you linked: 

3404#> * installing *source* package ‘htmlwidgets’ ...
3410#> Failed with error: ‘there is no package called ‘shiny’’
3490#> ERROR: configuration failed for package ‘openssl’
3851#> ERROR: dependency ‘openssl’ is not available for package ‘httr’
3898#> ERROR: dependency ‘httr’ is not available for package ‘gh’
3967#> ERROR: dependency ‘httr’ is not available for package ‘rvest’
4124#> ERROR: dependency ‘httr’ is not available for package ‘oai’
4198#> ERROR: dependency ‘gh’ is not available for package ‘usethis’
4232#> ERROR: dependencies ‘usethis’, ‘httr’ are not available for package ‘devtools’
4300#> ERROR: dependency ‘oai’ is not available for package ‘pangaear’
4397#> ERROR: dependency ‘httr’ is not available for package ‘ggmap’
4432#> ERROR: dependencies ‘httr’, ‘rvest’ are not available for package ‘tidyverse’
4447#> ERROR: dependencies ‘devtools’, ‘ggmap’, ‘pangaear’, ‘tidyverse’, ‘usethis’ are not available for package ‘ISRaD’

I think we definitely have too many package dependencies (131!), but are you sure that's what is causing the build failure? Seems like it may be a few specific packages that are failing for whatever reason and the errors are cascading through all the packages that depend on those failed packages. 

Anyway, I'll try and take a look at this this week, probably Tuesday or Wednesday.

**Comment by greymonroe** [comment]
Ok thank you. Yes, perhaps we can just trim out the unnecessary stuff. In fact, I would be ok removing the shiny app entirely. What do you think?

**Comment by jb388** [comment]
Sure, I don't think anyone is really using the shiny app any more. However we do describe it in the manuscript (ln 342:345), but we could just delete that paragraph. @coreylawrence any concerns with axing shiny?

**Comment by jb388** [comment]
@greymonroe Unfortunately I'm not making much progress with this. I'm not at all sure it will solve the problem, but maybe cutting shiny is a good idea. Seems possible it is the source of the problem, but I'm not at all convinced.

One thing I noticed is that some of the functions don't specifically import the packages that they use (i.e. #' @import). Could that be related to why these dependencies won't install in the builder environment?

Interestingly, we don't actually rely directly on that many packages. In fact, there are only 10 that we call explicitly (if we don't include all of the packages that are included within tidyverse, i.e. dplyr, tidyr, ggplot2, stringr, or the ones included with every R installation, i.e. base, utils, stats). However, many of those 10 packages have a ton of dependencies. The point is that I'm not sure what we can cut, other than shiny.

The Description file lists more dependencies than 10, but that's due to redundancies of tidyverse packages and the inclusion of two we don't actually use: e.g. I couldn't find where we call 'usethis' in any of the functions, nor 'plyr'.

**Comment by jb388** [comment]
Also, the builder link isn't working any longer. I tried to upload the tar.gz file, but I think since you are the maintainer, @greymonroe , you are the only one who can run it.

**Comment by greymonroe** [comment]
Hmm ok. Yes I think a thorough review of package dependencies could be warranted. Let’s first try to remove shiny and see if that solves it. Jeff do you want to go over that together so you can see the cran submission process?

Not sure what you mean by builder. Can you explain?

**Comment by jb388** [comment]
@greymonroe what I meant by builder was just this link: https://builder.r-hub.io/status/ISRaD_0.1.1.tar.gz-33874d571ec84bd1a505ee2a82956b2e

**Comment by jb388** [comment]
Sure, I'd be interested to learn more about the CRAN submission process.

**Comment by coreylawrence** [comment]
Sorry to be late to the party. I am totally fine with axing the Shiny interface. Since it isn't really served through the website, the intended utility isn't there anyways. We could always try to bring it back for the website at some point in the future (assuming we can find a good way around the hosting issue) but I don't see any need to include it in the R-package.

**Comment by jb388** [comment]
No worries, @coreylawrence. Definitely been to more fun parties. Thanks for weighing in. Let's go ahead and cut shiny; hopefully that will fix the problem.

**Comment by greymonroe** [comment]
Ok I’ll get going on this

**Comment by greymonroe** [comment]
Resubmitted to CRAN. fingers crossed. 

@jb388 Here is the code with the steps to release (or update) the package. 

```
# rebuild to make sure everything looks good
ISRaD.build(geodata_clim_directory ="~/Seafile/ISRaD_keeper/ISRaD_extra_spatialdata/", geodata_soil_directory="~/Seafile/ISRaD_keeper/ISRaD_extra_spatialdata/ISRaD_extra_soiltax", geodata_pet_directory = "~/Seafile/ISRaD_keeper/ISRaD_extra_spatialdata/pet/" )

# update minor version number 
ISRaD_directory<-getwd()
DESC<-readLines(paste0(ISRaD_directory,"/DESCRIPTION"))
version<-unlist(strsplit(DESC[3],split = "\\."))
version<-version[1:3]
version[3]<-as.numeric(version[3])+1
DESC[3]<-paste(unlist(version), collapse = ".")
writeLines(DESC, paste0(ISRaD_directory,"/DESCRIPTION"))

# the release() function will ask that you've done this so you might as well run now
devtools::document()
devtools::spell_check()
devtools::check()
devtools::check_rhub()
devtools::check_win_devel()

# this is to release to CRAN
devtools::release()
```

BTW do you want to become the official maintainer?

**Comment by jb388** [comment]
@greymonroe OK, thanks. Sure---I can take over official maintainer status.

**Comment by jb388** [comment]
@coreylawrence @aahoyt @ShaneStoner @greymonroe 
I pulled the problematic vignette (explore-fractions.rmd), switched the maintainer role from Grey to me, and rebuilt ISRaD for a new submission. But apparently the CRAN team is on vacation from August 9th til August 18th. No CRAN submissions possible during this time. I'll resubmit on the 18th and keep you posted.

**Comment by jb388** [comment]
@greymonroe I know you've passed on the title of maintainer, but I'm still running into this issue with the openssl configuration. The build works on the following platforms: 
* my local machine (mac 10.13.4)
* Windows Server 2008 R2 SP1, R-devel, 32/64 bit
* Ubuntu Linux 16.04 LTS, R-release, GCC
but it DOES NOT WORK for Fedora Linux, R-devel, clang, gfortran

I'm getting the same error as before (see report here https://builder.r-hub.io/status/ISRaD_0.1.4.tar.gz-e86d06be0e4a407787381ecf556c8ec1):

  4207#> ------------------------- ANTICONF ERROR ---------------------------
  4208#> Configuration failed because openssl was not found. Try installing:
  4209#> * deb: libssl-dev (Debian, Ubuntu, etc)
  4210#> * rpm: openssl-devel (Fedora, CentOS, RHEL)
  4211#> * csw: libssl_dev (Solaris)
  4212#> * brew: openssl@1.1 (Mac OSX)
  4213#> If openssl is already installed, check that 'pkg-config' is in your
  4214#> PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
  4215#> is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
  4216#> R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'

I don't know how to direct R to look at the proper configuration file when building on a remote server via docker.

**Comment by greymonroe** [comment]
Hmm could be part of a general issue with openssl 

https://github.com/swirldev/swirl/issues/513 <https://github.com/swirldev/swirl/issues/513>
https://github.com/rocker-org/rocker/issues/124 <https://github.com/rocker-org/rocker/issues/124>

Can you see which packages we require depend on openssl?

**Comment by jb388** [comment]
@greymonroe Pretty sure everything tidyverse depends on openssl in some recursive fashion.

**Comment by greymonroe** [comment]
Bummer. Really have no idea what this error is about. I would be shocked if every package that used tudyverse failed submission. You could always go ahead and try to submit anyway

**Comment by jb388** [comment]
> Bummer. Really have no idea what this error is about. I would be shocked if every package that used tudyverse failed submission. You could always go ahead and try to submit anyway
> […](#)
Right? I feel like I'm missing something simple here, or it should be easier to find a solution given the ubiquity of tidyverse dependencies. But it's hard to troubleshoot the issue since it only occurs with an install on a completely different system. I went ahead and submitted it to CRAN anyway, since it did pack all the checks on the other systems. So fingers crossed...

**Comment by jb388** [comment]
Fixed the Fedora platform config error. Had to change the PKG_CONFIG_PATH by installing openssl@1.1 w/ homebrew. Just as the error message suggested, hah. Package now ready for CRAN, just waiting on final edits/documentation of updated geospatial fxs.

**Comment by jb388** [comment]
And...we're finally on CRAN!
