### ISSUE TITLE
Central ISRaD_extra documentation

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#191]
Did we plan a place for centralized ISRaD_extra documentation? This came up yesterday during a training, when we realized there was nowhere for people to look up the variables.

As we have the Template Info file, it would be great to have a parallel document for ISRaD_extra variables.

Ideas on the best way to create this & ensure it stays up to date?

**Comment by greymonroe** [comment]
Can someone write a markdown file just explaining all of the changes?

**Comment by jb388** [comment]
Closing this as documentation exists now.
