### ISSUE TITLE
'ISRaD_data' is not an exported object from 'namespace:ISRaD'  

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#193]
@greymonroe 
I pulled the requireNamespace calls to the 'SoilR' and 'forecast' packages, since we decided to get rid of the predicted atmospheric 14C (forecasted data look terrible). 

When I tried to run the devtools::document function on the ISRaD directory to update the DESCRIPTION and NAMESPACE files, I got the following error:

Error: 'ISRaD_data' is not an exported object from 'namespace:ISRaD'  

I think this means we need to get rid of the .R files that corresponded to the (now absent) data objects, correct?

Edit: I removed them and seems to work. But is there any reason to keep them?

**Comment by greymonroe** [comment]
Exactly, yes we should delete those.

**Comment by jb388** [comment]
OK, I'll push my changes.

**Comment by greymonroe** [comment]
Are you going to delete them? I can too just let me know

**Comment by jb388** [comment]
yes, I deleted them
