### ISSUE TITLE
Add ISRaD extra documentation to the website

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#197]
In the midst of responding to reviews of the ISRaD manuscript and working with data for my Goldschmidt talk, I'm noticing a few things that need some attention. The first thing that comes to mind is that we do not have any documentation (at least that I can see) for the ISRaD_extra variables available via the website. There is some documentation of these variables in the manuscript, which can be easily reformatted for the web viewing. 

The first question is whether there have been any other additions to the "extra" dataset that are not already included in the manuscript table? #140, #146 

Second question, what is the preferred format for serving this information? Simple table? Vignette? Something else?

**Comment by jb388** [comment]
@ShaneStoner I know you were working on this recently---have you uploaded any files/made changes to the website?

**Comment by coreylawrence** [comment]
I went ahead and added a short description of raw vs. extra data files to the [Database](https://international-soil-radiocarbon-database.github.io/ISRaD/database/) section of the website. I also linked the ISRaD_Extra_Info file that Shane created.

We probably need to clean this section of the website up a bit but it should be good enough for now.
