### ISSUE TITLE
Depth Conventions

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#2]
We need to settle on a convention for reporting depths in the template/database. 

Option 1. The surface/atmosphere interface of the soil is set to zero. Values increase (positive values) with increasing depth in the profile. With this option, we need include a flag for layer increments to either define each as organic/mineral or to set the depth of the interface so that those flags can be generated automatically. 

Option 2. The zero point is set at the organic/mineral interface. Values increase (positive values) with increasing depth in the mineral soil and decrease (negative values) with increasing distance above the organic/mineral interface. The issue with this option is that, for some samples, one might not know the depth to the organic/mineral interface - in that case the convention cannot be applied accurately.

It seems that the general preference is for option 1. If you have a different perspective please add a comment here, explaining your reasoning.

**Comment by greymonroe** [comment]
Yea it sounded like option 1 was favored but we can leave it open to discussion here for a bit before making a todo item to switch over the template, template info file, and current templates with data to reflect the change.

**Comment by jb388** [comment]
What's the current thinking on this, team? I still support atmospheric interface as the zero point, with an added mineral/organic flag. Perhaps we should discuss again in September at the hackathon?

**Comment by ktoddbrown** [comment]
As long as the convention is adhered to, we can convert the negative depth numbers. What is the issue you are seeing with this @jb388 ?

**Comment by ktoddbrown** [comment]
Scraping off the organic layer actually says to me that we should use the 0 for the mineral/organic interface otherwise we have an unknown offset from the surface of the soil. We'll run into some issues either way with that kind of data.

**Comment by greymonroe** [comment]
can this be closed?

**Comment by jb388** [comment]
I was leaving this open as a reminder to build the report tool that converts the depths.

**Comment by jb388** [comment]
@greymonroe I think this would be a helpful function. I would also make sure the function adds a column that specifies whether the layer is organic or mineral, so as not to loose that important information.

 I'm not sure that this should be an israd.extra function, but maybe just a helper tool? I.e. I don't see a need to automatically add these columns to the ISRaD_extra objects, as they may be confusing or just unnecessary for most users.

Also, I have some code that does this exact thing, but I haven't looked at it in a while. Probably not high priority to implement, but I could do it sometime in the next month or so.

**Comment by greymonroe** [comment]
moving to new issue requesting ISRaD.extra.depth
