### ISSUE TITLE
read_EstopAragones fx causing install problem

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#201]
@ShaneStoner 

I was getting installation issues with ISRaD after the read_EstopAragones fx was added back in. I tried a bunch of fixes for it---assuming the issue was local---but the only thing that fixed the problem was pulling that EA fx back out of the package.

There was a "cyclic namespace dependency" error, which was preventing me from re-installing/updating ISRaD to the latest github version. I'm thinking it's from ln 11 in the EA script, which calls install_github itself (seems circular, right?) 

Maybe it's best to keep the EA fx out of the ISRaD/R directory for now---the ISRaD/inst/extdata directory could work?

**Comment by ShaneStoner** [comment]
I don't think I added it, and since we aren't using those files yet (as they aren't verified), I don't see any reason to keep the function in the package at all at this time. 
Yes that seems very circular to me! More work to do on that function.
