### ISSUE TITLE
broken links on website

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#204]
Links to template and template info file are now broken on the website (e.g. from Contribute page or Database page). Possibly due to re-org of the repository for CRAN? Or website changes?

**Comment by jb388** [comment]
Hi Alison, yes the links are broken due to the directory structure change. The template and template info files can now be found, but they aren't currently loading with the .xlsx viewer; also clicking the link takes you to the github page---is that what happened before?

**Comment by jb388** [comment]
Oh, and there may be additional links that need updating for the same reason. Keep an eye out for broken ones.

**Comment by jb388** [comment]
OK, seems resolved. Just reopen issue if still unable to download files.
