### ISSUE TITLE
Soil grids data nomenclature

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#206]
There are discrepancies between the names of the soil grids (SG) variables in the ISRaD extra object and the descriptions in the ISRaD_Extra_Info.xlsx file. There are two issues: 
1) Depths are not consistent with what is reported on the ISRIC site (i.e. we have 10cm data, but SG only reports estimates at target depths of 0cm, 5cm, 15cm, etc.
2) Only clay and a generic soil carbon variable are described, but we have more data in the extra object, vis. bulk density, soil carbon stocks, and coarse fragment content.

@ShaneStoner Did you pre-process these data at all? I know I changed the names when I had to shorten them, but I don't recall changing the depths (nor can I imagine why I would do so, but hey, I wouldn't put it past myself to have done so). If you didn't do any pre-processing, I can just change the file names so they correspond to the right depths.

**Comment by ShaneStoner** [comment]
The ones on the ISRIC website are outdated then... I don't know exactly 
why that would be. However, there are new updated datesets at this link 
<https://zenodo.org/record/2536040#.XdwCeTJKh25>, also from Thomas Hengl 
but released at the end of last year. They use different depth 
conventions. I believe there was a systematic error in the older files 
(predicted way too much carbon globally).

**Comment by jb388** [comment]
Nice, thanks @ShaneStoner 
But the BD, clay, OC concentration, and coarse fragment files ARE from the soil grids site, correct? In which case the depths should be changed.

**Comment by jb388** [comment]
Ah, sorry, didn't follow all the links on Zenodo. OK, cool. I will update the web references as needed to point to the new files rather than Soil Grids.
