### ISSUE TITLE
Website user manual issue

### ISSUE THREAD

**Issue by CaitlinPries** [International-Soil-Radiocarbon-Database/ISRaD#208]
2) Install package 'ISRaD' from the development branch of our github repository:
devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD", ref="master", force = T)

Should read (add /Rpkg to address)

2) Install package 'ISRaD' from the development branch of our github repository:
devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD/Rpkg", ref="master", force = T)

**Comment by ShaneStoner** [comment]
Hi Caitlin! Thanks for pointing it out. Should be fixed now.

**Comment by olgavinduskova** [comment]
Hello!
I came across the same bug pointed out by Caitlin now (when clicking through website -> R package -> Tutorial here -> https://soilradiocarbon.org/_pages/user_manual_Aug15_2019.html)

**Comment by ShaneStoner** [comment]
Ahhh I fixed it in the R markdown file the first time. Fixed it in the html this time.
