### ISSUE TITLE
Improve build fx efficiency

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#209]
The build function performs QAQC on all files in the data directory, which is inefficient given that the majority of templates already pass. Proposed solution: check QAQC file names against template names (verify that QAQC passes), and then only QAQC new templates.

**Comment by alkalifly** [comment]
That would be great. But it should also check that the modification time of the QAQC file is later than that of the template file. That way, if an existing template gets updated, the new version will get checked.

**Comment by coreylawrence** [comment]
I second Paul's comment. There are instances where templates that have passed QA/QC have been updated in the repository. Of course, any changes should be run through the QAQC processes before being implemented but it would be best to double-check.

**Comment by jb388** [comment]
I spent some time working on this today and made some initial progress. Changes to 'compile.R' are on the dev branch.

Specifically, the function now 1) checks if the template is in the database already, and 2) if it is, checks whether the data are all the same. QA/QC is only run if either 1) or 2) are FALSE. 

@alkalifly I decided to use the actual data as the test, rather than the modification date.

The primary efficiency improvement remaining is in the ISRaD_extra process. Similarly to compiling the database and running QA/QC, I'd like to run the ISRaD_extra functions only for the new data. That's a project for another time, however...

**Comment by jb388** [comment]
Update: new compile function is now on master. 

While going over performance of the new function again today, I actually caught an instance where strange characters had been inserted in the ISRaD_list.xlsx file: e.g. the Caner_2003 template has the character "<" in the frc_name field, which was parsed as "&lt;". 

So, I guess another advantage of the new function is that it provides a mechanism to catch these sorts of errors, i.e. discrepancies between data as entered in the template and as rendered in the compiled data product.
