### ISSUE TITLE
frc_obs_date and inc_obs_date fields misleading

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#211]
@aahoyt @ShaneStoner @coreylawrence 
The frc_obs_date and inc_obs_date fields were intended for recording the date when the samples were processed in the lab. I don't find this to be useful, and in fact, I think it is both confusing and potentially misleading. Some of our ISRaD_extra functions use the date fields (e.g. to fill 14C/fraction modern/delta-delta), and those functions actually need the lyr_obs_date_y in order to work properly. I propose removing these columns (note that they are not required by QAQC).

**Comment by coreylawrence** [comment]
I agree that this is confusing. In comparing the frc_obs_date_y and lyr_obs_date_y across some fraction data, I noticed that the values are occasionally different. Presumably this could be because samples were fractionated at a different time but perhaps that information would be better captured in the frc_rc_year field?

**Comment by jb388** [comment]
I think I was overthinking this. The incubation date fields are definitely useful for recording time series. Since the fraction table was intended to capture a wide range of possible fractionation schemes, I suppose there may be some cases in which it would be helpful to capture temporal data? I can't think of anything off-hand though. 

If not, we could remove frc_obs_date fields, but we should definitely keep the incubation ones.

**Comment by jb388** [comment]
I'm going to go ahead and close this, but feel free to reopen if you want to discuss further.
