### ISSUE TITLE
Website link not working

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#213]
@aahoyt @ShaneStoner 
The ISRaD website doesn't seem to be working. I get the following message on Firefox when trying to load the page:

Secure Connection Failed

An error occurred during a connection to soilradiocarbon.org. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

A similar message is returned with Chrome:

This site can’t be reached
soilradiocarbon.org unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_CLOSED

**Comment by jb388** [comment]
Note that the website seemed to be working fine just an hour ago.

**Comment by jb388** [comment]
Also, could the domain name have expired?

**Comment by coreylawrence** [comment]
I'm seeing the same problem with Firefox and Chrome. My guess is that this is a domain name issue but maybe @aahoyt can clarify that.

**Comment by coreylawrence** [comment]
It appears to be back up now. Any word on what was the cause of the problem?

**Comment by aahoyt** [comment]
Domain name expired since we only had it for one year. I just paid for 5 more years, so we are good til Jan 10, 2025! Some time in the next five years we should set up autopay ;)
