### ISSUE TITLE
QAQC is not requiring ist_name to be entered

### ISSUE THREAD

**Issue by olgavinduskova** [International-Soil-Radiocarbon-Database/ISRaD#214]
an accidental discovery - I forgot to enter ist_name in the interstitial tab and QAQC did not recognize it (even though it seems to be a required column) .

**Comment by jb388** [comment]
Thanks for bringing this up, @olgavinduskova 

The ist_name column is actually not required. My recollection is that when the interstitial table was first created we didn't have a field for ist_name, so when it was implemented later there were entries missing data in that field (compare "inc_name" in the incubation table). Additionally, the field serves as an internal reference for that table only---in the sense that it is not a relational key that is referenced in any of the other database tables (unlike "lyr_name", "pro_name", etc.).

So, while I would say "ist_name" is strongly suggested, I don't think it's necessary to make it required.

**Comment by olgavinduskova** [comment]
I see! I got confused by ist_name being in red font in the template but I guess that is expressing the strong suggestion to enter it :))

Actually, when I forgot to enter ist_name and I entered data from several depths of the same profile, QAQC gave me "Duplicate interstitial row identified." warning, even though all combinations of pro_name and ist_depth were unique. When I entered the ist_name, this warning disappeared. So I assume that the duplicate check is considering pro_name + ist_name (and not considering ist_depth) and therefore indirectly actually requiring ist_name to be entered.

**Comment by jb388** [comment]
Thanks for noticing this Olga. I'll check the entries currently in ISRaD to see if any will fail QAQC if ist_name is changed to a required field. As you point out, the duplicate row identification function should make that pretty much impossible, unless there were single observations per profile. But it would probably be more clear to users if we just changed it to be required.
