### ISSUE TITLE
QA/QC not working from website

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#238]
Running QA/QC from the website now shows this error: 
"Github App international-soil-radiocarbon-database/ISRaD not installed on this server"

Maybe an opencpu issue? Not sure how the last updates to the repo could have caused this problem.

**Comment by jb388** [comment]
FYI, QAQC function works fine directly from the R console. Again, points to opencpu as the culprit.

**Comment by jb388** [comment]
OK, looks like opencpu pushed a new update on 3 July 2020, so that seems likely to be the cause. Will look into this further in the near future. Hopefully a simple fix.

**Comment by kjmcfarlane** [comment]
In the meantime, can you point me to the R script?

**Comment by coreylawrence** [comment]
Hi Karis, 

If you install the ISRaD R package as follows (note that you will need to install 'devtools' if you haven't already:
`devtools::install_github("International-Soil-Radiocarbon-Database/ISRaD", ref="master", force=TRUE)
library(ISRaD)`

You can run the QAQC report function using:
`QAQC("filename", writeQCreport=F)`

If you'd like to save a .txt copy of the report output, you can change that option to TRUE. However, you will need to manually create a folder named "QAQC" in the same directory where the file is located - otherwise it will spit back an error message.

Cheers,
Corey

**Comment by SophievF** [comment]
Hi everyone,
You can also use the compile function if you would like to run QAQC for more then one template at the same time:

compile(dataset_directory = "YourDirectory",  write_report = T, write_out = T, return = "list")

You have to make sure that all the templates you want to check/compile are in "YourDirectory" folder and the function creates a QAQC folder with the reports within the same folder.

**Comment by SophievF** [comment]
Note: the QAQC function itself (when directly called as Corey it describes) is checking for the doi and may tell you that the doi is not valid (even though it is correct). Within the compile function check doi is set to FALSE by default.

**Comment by jb388** [comment]
Just to chime in: as @SophievF says, when you run "compile.R" the DOI check functionality of the internal QAQC call is suppressed. This is a known issue with the way that the DOI check works. Unfortunately, when the DOI check queries the online server to validate the DOI, it is not uncommon for the request to time out, which can result in an erroneous "DOI not valid" response. 

This is the reason that the compile function does not check the validity of DOIs---because beyond a certain number of entries it is almost inevitable that some of the DOI check requests will time out, which will then abort the compilation process.

I would recommend still running QAQC as a standalone function for each entry that needs to be checked. An alternative to batching this process would be to embed the QAQC function in a for loop.

**Comment by bpbond** [comment]
Hi @jb388 happy to do something if I can help, but not sure why this was just assigned to me. Thanks!

**Comment by jb388** [comment]
> Hi @jb388 happy to do something if I can help, but not sure why this was just assigned to me. Thanks!

@bpbond Sorry---no pressure, we just keep running into dead ends with this issue even though it seems like it should be a simple fix. I thought there was a chance you may be more familiar with this sort of thing.

**Comment by bpbond** [comment]
I don't offhand, sorry, though got interested looking through [Rpkg/inst/www](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/tree/master/Rpkg/inst/www) just now. Is there documentation or an URL for this functionality?

**Comment by jb388** [comment]
> I don't offhand, sorry, though got interested looking through [Rpkg/inst/www](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/tree/master/Rpkg/inst/www) just now. Is there documentation or an URL for this functionality?

We've been using the [opencpu](https://www.opencpu.org/api.html) package to host ISRaD on a remote server and run the QA/QC script via html (so users don't have to have R installed to run QA/QC on an entry). Here's the [opencpu manual](https://opencpu.github.io/server-manual/opencpu-server.pdf). This was setup by our original maintainer @greymonroe who has since left the project. It was a simple and elegant solution, but unfortunately it appears to have been broken somehow in the latest opencpu update. The key issue seems to be that we have our R pkg in a subdirectory, rather than in the top level directory of the repo. 

Again, don't feel obligated to spend time on this, I assigned you on the outside chance you were familiar with this sort of thing. So no worries.

**Comment by jb388** [comment]
Oh, just to note that I moved the Rpkg to the sub directory 9 months ago, but the issue only cropped up about a week ago, coinciding with a new release of the opencpu package on July 3rd. That said, I couldn't easily identify anything in their latest commits that seem to relate to our specific issue.

**Comment by jb388** [comment]
Thanks to @ShaneStoner, we fixed the issue. We are know running QA/QC as a shiny app. This has the additional benefit of providing a basic platform for all the shiny functionality we've talked about rebooting over the years.
