### ISSUE TITLE
Compiled studies list - formatting issue

### ISSUE THREAD

**Issue by kjmcfarlane** [International-Soil-Radiocarbon-Database/ISRaD#240]
The list of studies included in the current version is linked from the website here: https://github.com/International-Soil-Radiocarbon-Database/ISRaD/blob/master/ISRaD_data_files/database/credits.md
Some of the citations include a lot of extra stuff that seems copied from the paper websites or ???
Not the most important issue, but annoying and hopefully an easy fix!

**Comment by jb388** [comment]
More complicated than expected, but fixed!
