### ISSUE TITLE
ISRaD version 1.4.5 is missing lyr_dd14c and lyr_graven_atm 

### ISSUE THREAD

**Issue by christinaschaedel** [International-Soil-Radiocarbon-Database/ISRaD#241]
the newest ISRaD version 1.4.5 (and I believe the previous release from March too) is missing lyr_dd14c and lyr_graven_atm values, Do I need to calculate them myself or are they supposed to be provided in the extra version of ISRaD? @jb388

**Comment by jb388** [comment]
@christinaschaedel thanks for noticing this. I should be able to fix that today, but I will leave the issue open until it's fixed.
