### ISSUE TITLE
misplaced quotes in code examples on R package home page

### ISSUE THREAD

**Issue by brownag** [International-Soil-Radiocarbon-Database/ISRaD#243]
Not sure if this is the right place to post this, but should be a simple fix for whoever is responsible for the website (https://soilradiocarbon.org/rpackage/)

```
# set 'directory' argument to local path
ISRaD.getdata(directory = "~", dataset" = "full, extra = "TRUE", force_download = "TRUE")
```

 should be

```
# set 'directory' argument to local path
ISRaD.getdata(directory = "~", dataset = "full", extra = "TRUE", force_download = "TRUE")
```

Typo is also repeated in next section:

`ISRaD.getdata(directory = "~", dataset" = "full, force_download = "TRUE")`

Thanks for the package, I think this is a great way to deliver the data.

**Comment by jb388** [comment]
@brownag Nice work, thanks for catching this. Should be fixed now. Glad you're finding the R package helpful.
