### ISSUE TITLE
How to handle depth when only mid-depth is reported?

### ISSUE THREAD

**Issue by ShaneStoner** [International-Soil-Radiocarbon-Database/ISRaD#245]
Ágatha has been entering data on thermal fractions, and a synthesis by Hemingway et al. (2019) only reports mid-depths, and these records in the original papers either don't include depth or are impossible to match records. 

I feel like we have encountered this problem in the past, and I don't know that we've decided on a method for handling it. Ágatha and I (with some input from Jeff) have discussed a 1 cm depth increment (lyr_top = 44, lyr_bot = 45), or setting top and bottom both equal to the mid depth. This is maybe the least misleading way to handle it?

Would welcome any input! @coreylawrence @aahoyt @crlsierra @setrumbore

**Comment by setrumbore** [comment]
Can we ask Hemingway?

Sue

Susan Trumbore
MPI for Biogeochemistry

**Comment by ShaneStoner** [comment]
Just sent him an email, we'll see what happens. Maybe this is an easy fix, but should we have a policy of requiring top and bottom depths to be distinct from one another? Some of the soils used here actually do have a 1 cm depth range, so flagging those as not specified properly would be wrong in this case.

**Comment by jb388** [comment]
Just a note for posterity that when we were designing the ISRaD template we discussed this issue and I believe our conclusion was that if only the mid-depth was reported than we shouldn't enter the data in ISRaD, being of only limited use without upper and lower bounds.

Hopefully you managed to contact Hemingway!
