### ISSUE TITLE
ISRaD_Extra pro_KG variables should have categorical key

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#247]
I just discovered that we have been serving up Koeppen-Geiger class data in ISRaD_Extra with minimal documentation. The data are described in the geospatial readme file in the ext dir of the R package, but were missing in the ISRaD_Extra_Info file (just added now).

It would be helpful to add a geospatial key file for these data, as the numerical classifications are not easy to interpret as listed.

**Comment by SophievF** [comment]
I added a csv file to convert the numbers into the actual climate zones
