### ISSUE TITLE
Roots and litter incubations

### ISSUE THREAD

**Issue by agathadrk** [International-Soil-Radiocarbon-Database/ISRaD#249]
Hi All,

I have a doubt about entering roots and litter incubations. 
For roots, would the path be: Layer (for more details on lyr_top and lyr_bot) -> Fraction (frc_property: roots) -> Incubation (referring back to the corresponding layer and fraction)? 

For litter I suppose it would be similar, but there is no "frc_property" referring to it. Should the path be: Layer -> Fraction -> Incubation or only Layer -> Incubation?

**Comment by jb388** [comment]
Hi Ágatha,
Your intuition about roots is correct: Layer (for more details on lyr_top and lyr_bot) -> Fraction (frc_property: roots) -> Incubation (referring back to the corresponding layer and fraction).

We have treated litter conceptually as its own layer, not a fraction. So you would enter the litter lyr_top, lyr_bot in the layer table (using negative values for lyr_top/lyr_bot), and then reference the layer record in the incubation table, i.e. Layer -> Incubation.

Hope that helps clarify.

**Comment by agathadrk** [comment]
Great! Thanks a lot Jeff. 

This clarifies all my questions. I used for litter depth -5(lyr_top) and 0(lyr_bot).
