### ISSUE TITLE
pro_depth_water

### ISSUE THREAD

**Issue by agathadrk** [International-Soil-Radiocarbon-Database/ISRaD#250]
I am entering a study where a drainage experiment was performed on a gelisol in Chersky. 

In the "pro_depth_water" the depth to the water table was 5.0 ± 2.8 cm in the drained profile, but -1.0 ± 3.1 cm (denoting standing water above the soil surface) in the control profile. 

Looking at the ISRaD template information, there is a limit of only allowing positive values, since the depth to the water table is mainly below ground in mineral soils. But I would suggest changing the minimum and maximum levels, since water above the soil surface is common in those drainage experiments and also in peatlands. 

Also, adding the terms below and above ground in the description would make it easier. Since often in peatland studies, positive values are denoting water standing above the ground surface and negative values of water standing below the ground surface (contrary to the ISRaD convention), making it more difficult to fill in the "pro_depth_water" values correctly.

**Comment by jb388** [comment]
Thanks for pointing this out. This sounds like a smart change to allow us to record peatland data more accurately. I can update the ISRaD template info sheet accordingly.

**Comment by jb388** [comment]
OK, template info file has been updated, so I will close this issue.

**Comment by agathadrk** [comment]
Thanks Jeff, 
This will be of great help with the peatland templates.
