### ISSUE TITLE
ISRaD Extra List populating 14C and SD columns with same values? 

### ISSUE THREAD

**Issue by hedgpea** [International-Soil-Radiocarbon-Database/ISRaD#253]
Hello, 
It looks like in the ISRaD extra file the frc_14c, frc_14c_sigma, and frc_14c_sd are all the same values. It also looks like the layer sheet has the same issue. 
Is this happening for others who download the sheet "manually" i.e. without using the R code? 
Thanks!
Alex

**Comment by jb388** [comment]
Hi Alex,
Thanks for pointing this out. We noticed this a few months back, and I thought it had been resolved, but sure enough the flat files from April 26th 2021 still seem to have the same issue. I'll take a look, and also rebuild ISRaD to incorporate your new data.

Cheers,
Jeff

**Comment by hedgpea** [comment]
Thanks so much Jeff! Appreciate all you’re doing for the database!
Alex
