### ISSUE TITLE
Citation of repository

### ISSUE THREAD

**Issue by ktoddbrown** [International-Soil-Radiocarbon-Database/ISRaD#256]
Could we add a citation guide for the repository itself? I'm trying to cite this repo for a manuscript and this is what I have so far:

> @misc{israd_git,
>     title = {International Soil Radiocarbon Group: R package},
>     author = {ISRaD contributors},
>     url = {https://github.com/International-Soil-Radiocarbon-Database/ISRaD},
>     year = {2018-2021},
>     howpublished = {Accessed: Nov. 2021}
> }

@coreylawrence @aahoyt @SophievF @ShaneStoner Thoughts?

**Comment by bpbond** [comment]
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by jb388** [comment]
Thanks for pointing this out, @ktoddbrown , and thanks for the tip on adding a .cff file @bpbond 

We now have a [citation file](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/blob/master/CITATION.cff) at the root of the repo. I used the most recent release for the citation (7-Jan-2021). We don't have a DOI for that release (it was only to github), but it matches the most recent CRAN submission so I thought it would be most appropriate.
