### ISSUE TITLE
Missing data source for geospatial data

### ISSUE THREAD

**Issue by SophievF** [International-Soil-Radiocarbon-Database/ISRaD#262]
@jb388: For some of the geospatial data (e.g. USDA soil type, koeppen geiger climate zones) the data source is missing in the ISRaD_Geospatial_Data_README file

**Comment by jb388** [comment]
@ShaneStoner Do you have any ideas about this? I know you did a lot of work with the geospatial data early on in the project.

**Comment by coreylawrence** [comment]
I had a look at the file in question. There is currently a source listed for the Koeppen but the USDA soil type source is missing. I wasn't involved in the geospatial extraction that is represented by this file and am not familiar with the source for the USDA values. Hopefully, @ShaneStoner has the details.

**Comment by jb388** [comment]
Resolved
