### ISSUE TITLE
Found doubles of Gaudinski 2001

### ISSUE THREAD

**Issue by CaitlinPries** [International-Soil-Radiocarbon-Database/ISRaD#267]
I was running some code I had from the last build of the database on the new build and found a couple issues. One is that at least 17 heavy fractions (I did not check LF, but I am guessing those would be duplicated in the same layers) that were duplicates (see attached csv). They are not repeated in the "Gaudinski_2001_Trumbore_unpubl" datafile so they have to be from somewhere else? I looked briefly but could not find where.

[gaudinski_2001_doubles.csv](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/10045799/gaudinski_2001_doubles.csv)

**Comment by jb388** [comment]
Fixed---updated version of database solved the issue.
