### ISSUE TITLE
Update delta-delta calculation with new atmospheric dataset

### ISSUE THREAD

**Issue by setrumbore** [International-Soil-Radiocarbon-Database/ISRaD#269]
The latest version of SoilR includes the updated (to 2019) atmospheric values.  Especially in the southern hemisphere, the old extrapolations are not in good agreement.  For example, looking at the Sheibe_2022  2019 southern hemisphere atmosphere is extrapolated to be -8 permit, while the Hua et al. update gives +11 per mill.  Since we no longer need to extrapolate, can we revise the R code to update to the newest atmosphere data?   For extrapolation to 2020 and beyond I would use the 2019 values and subtract 3 per mil per year rather than use the older versions.  (Thanks, Sue)

**Comment by jb388** [comment]
This is a good suggestion. However, there is a slight issue in that the [Graven et al. (2017)](https://doi.org/10.5194/gmd-10-4405-2017) dataset we have been using for ISRaD up to now is both simpler (fewer atmospheric zones, e.g. single NH/SH zones), lower resolution (annual), and starts earlier (1850 vs. 1941) than than the [Hua et al. (2021)](https://doi.org/10.1017/RDC.2021.95) data set. The simplest approach may be to keep the Graven et al. (2017) dataset and add in the Hua et al. (2021) dataset as an optional choice for individual users when filling atmospheric 14C and calculating delta delta values on their own. 

The challenge with using the Hua et al. (2021) dataset in the ISRaD extra functions is determining the correct atmospheric zone for each profile. Hua et al. (2017) do not provide a geospatial file of the zonal boundaries that would facilitate this. In contrast, Graven et al. (2017) simply divide the globe into three zones: NH (north of 30° N), tropics (30° N to 30° S), and SH (south of 30° S).  

For now, I would propose we continue using the Graven dataset for building the ISRaD_extra object, but put an optional argument in the ISRaD.extra.calc_atm14c and ISRaD.extra.delta_delta functions allowing users to select the Hua2021 data as the data source when doing their own calculations. Thoughts?

@aahoyt @setrumbore @coreylawrence @crlsierra @CaitlinPries @SophievF @ShaneStoner

**Comment by setrumbore** [comment]
Hi Jeff 
I confess I have not checked agreement between Hua and Graven from 1980-2017.
But as you say the Hua 2021 record is basically NH and SH. As it is the only published recorded we have and we know that the extrapolations based on Heather’s record do not work well for the Southern Hemisphere, I would prefer to use the Hua record (annual) for now

What is sad is that Ingeborg and Heather and Xiaomei all have more recent data but mostly Ingeborgs records agre with Hua

Sue

**Comment by jb388** [comment]
Update:
I've added the Hua et al. (2021) dataset to ISRaD, and the data object is "Hua_2021". I chose this name so as not to mask the version in SoilR, as the version in ISRaD is summarized to yield annually resolved northern and southern hemisphere records (raw data in SoilR has five atmospheric zones and includes sub-annual data). The Hua_2021 data object is now used for filling atmospheric data, but only resolved to two atmospheric zones: north (> 0 deg latitude) or south (< 0 deg latitude).

The Graven et al. (2017) data is still in ISRaD, but has been renamed "Graven_2017". The atmospheric record is longer, which is useful for spinning up the one pool model used in the normalization function. Additionally, the Graven et al. data also contains global 13C data, which I think is nice to have. 

I believe these changes should have minimal impact on existing code as implemented. Closing this issue now, but if anyone wants to chime in on this, feel free to reopen or post a new issue.
