### ISSUE TITLE
Excel in R package

### ISSUE THREAD

**Issue by ktoddbrown** [International-Soil-Radiocarbon-Database/ISRaD#28]
https://github.com/International-Soil-Radiocarbon-Database/ISRaD/blob/7c5d1da937b838f9f4c007e84b235235dd47f2bc/R/compile.R#L45

This might be better represented as a csv or text string instead of associated the excel file with the R package. This will make the package smaller and means that we don't need to run this as a package first. Excel updates their file meta data every few years and this will frequently cause incompatibility issues so I would hesitate to rely on this as a fundamental part of the package.

Thoughts?
-Kathe

**Comment by greymonroe** [comment]
at this point we are committed to using excel for the template. if things break in a few years we can address this issue again.
