### ISSUE TITLE
Date Reporting in Excel Templates

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#3]
An issue arises when relying on a single column to report dates in the excel templates. My understanding is that excel stores dates in a numeric form that is referenced to some benchmark date. The benchmark date, however, varies depending on what version of excel you are using (?!) and thus, when dates are ingested into the R data.frame, there is a potential for values to be off by up to 4-years.

One possible solution is to change the template to include separate columns for day, month, and year. This approach raises the question of whether we should also include hour (for flux or incubation data) or if we can simply address this by allowing for decimal days to be reported in the days column. 

Thoughts on this topic are welcome before we make a final decision for how to handle this moving forward.

**Comment by greymonroe** [comment]
Seems that being four years off is unacceptable. Let’s give a few days for people to weigh in though and unless there are objections we will then move this to the projects page as a to do item to add the new columns to the template.

**Comment by jb388** [comment]
Following up on this discussion and our most recent group phone call, I am officially proposing that we update all templates to include separate date fields for YYYY, MM, DD. This is a fairly easy task that I can pass along to our student helpers at MPI. Additionally, many entries are missing observation dates, so I this is an opportunity to flag these entries and find a solution for gap-filling.

**Comment by greymonroe** [comment]
being dealt with in issue #14

**Comment by greymonroe** [comment]
should be fixed in recent pull by @jb388
