### ISSUE TITLE
Issues with flat file output

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#34]
issues with flat file:
-not correctly capturing all hierarchical relationships 
-interstitial seems to be reading into wrong place
-interstitial and layer shouldn't be on the same line unless the depth is the same
-also conflict between interstitial and fraction

e.g. Gaudinski_2001:
-Is interstitial is being treated as the terminal node? Layer and incubation 14C values are repeating many times for each interstitial value. Problematic for multiple reasons: 
- On a given line of the flat file, depths of interstitial and layer are in conflict
-Incubations should be a terminal node (layer data should be on same line as incubation; also could include fraction if depths align)
-Where fractions are treated as terminal node, interstitial is repeated over & over, which also doesn't make sense if depths do not align
-If fractions are end of the hierarchy, why are frc_names are repeating? perhaps doing all permutations instead of building a hierarchy?

additional notes:
-what are all the extra columns showing up for me at the end?
-still compiling with lyr_non_bulk;  didn't we plan to remove this?

**Comment by greymonroe** [comment]
being managed in a more recently posted issue #58
