### ISSUE TITLE
compile output - delete description rows?

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#39]
The first two rows of the compiled R object (output from compile function ) under the header are the column descriptions.

 Are we ok to delete these from the compiled output R object? They are clumsy to work with, and most (all?) users will be deleting them prior to anlaysis.

We should definitely leave them in the output excel file (the "mega template") so that it will be able to compile with other templates.

**Comment by greymonroe** [comment]
the excel file still saves with the top two rows. but the returned item in R should have no description rows now.
