### ISSUE TITLE
Kruger data from Khomo 2017

### ISSUE THREAD

**Issue by Kate-Heckman** [International-Soil-Radiocarbon-Database/ISRaD#4]
Something is wrong with the C and N data associated with this publication in the database. The N values are given as 10 % or more for mineral soils. The C numbers look odd as well - too low to match the figures in the manuscript. Something went screwy here.

**Comment by greymonroe** [comment]
is  correct in the data template file?

**Comment by greymonroe** [comment]
Is it correct in the data template file?

**Comment by Kate-Heckman** [comment]
I can’t tell. There’s multiple versions of the Khomo template on google drive, but none of them use the same site labeling scheme that’s in the compiled database download that Corey gave me in May 2017.

There’s so much stuff in the Khomo file I can’t tell what is what:

https://drive.google.com/drive/folders/0B4V_Q44oiEnoNTNuZ2tqNGNnUWM

**Comment by coreylawrence** [comment]
The completed template files do no live on Powell Center Drive folder. I will send through version that is ingested in the database, which are stored in a non-public dropbox account until we make the official database release. 

That said, I see that there are two files for the Khomo dataset in the ISRaD_data folder. Not sure why that is but hopefully the duplicate identification scripting that will be completed this summer should help remedy that.

**Comment by greymonroe** [comment]
data files should be in the ISRaD_data folder on dropbox (Kate, I sent you a link)

**Comment by jb388** [comment]
Just to chime in on this: the MPI group added incubation data to the Khomo 2017 entry, hence the multiple versions (the Powell Center entry only had bulk and fraction data). I checked the data in the MPI Khomo 2017 template and they match what is in SI Table 1 from the paper.

**Comment by coreylawrence** [comment]
I believe this issue has been resolved and can be closed
