### ISSUE TITLE
written permission from Claire Treat

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#41]
Claire Treat's data is under the following terms:
S1: "Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported (CC-BY-NC-ND)"

So, we need to archive written permission from her to use it.
Maybe we can start a folder where we store written permission & decide how to handle this?

Also, how will this propagate for products derived from ISRaD? Would they still need to get permission from the original author for the derivative product, or after it is "ISRaD" then is it ok?

**Comment by jb388** [comment]
Do we have this? Can we close the issue?

**Comment by jb388** [comment]
Thanks, @aahoyt ! Just a note: the "data" directory has special requirements for R, so I renamed the file (CRAN doesn't abide spaces) and moved it ("/ISRaD/inst/extdata/Treat_ISRaD_letter.docx").
