### ISSUE TITLE
Online QAQC not up to date

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#46]
Is there a reason we are intentionally not linking the online QAQC to the latest version? Or is this something we could change? 

For example, currently something that passes QAQC tool online may not pass the package version of QAQC. Is this just a dev/master branch difference or is something else going on? At the moment, it would be much more helpful if the online tool reflected all changes in the latest template/template info file

**Comment by greymonroe** [comment]
The online qaqc function looks to the master branch. We will need to merge dev and master to update the online tool, which is fine
