### ISSUE TITLE
Adding elevation column to profile tab

### ISSUE THREAD

**Issue by ShaneStoner** [International-Soil-Radiocarbon-Database/ISRaD#48]
Hey everyone,
After hacking all week, @aahoyt @alkalifly and I discussed the potential need for non-required elevation at the profile tab in addition to the required field at the site tab. This would help eliminate bloat at the site level, and prevent loss of data in studies with fine-scale geographic information, i.e. elevation gradient studies. Profiles would inherit elevation data from site unless data is entered on the profile tab, just like lat/long do currently. We could adopt this moving forward, or if someone was motivated it could be added to previously ingested studies.

I don't think this would cause too many problems that a script or two couldn't fix. Let me/us know what you think.

**Comment by greymonroe** [comment]
sounds fine. adding non-required columns wont affect the QAQC so no need to go back and change old data files unless we want to add the data.

**Comment by jb388** [comment]
Seems like no major concerns. I will go ahead and add pro_elevation to the Master template and info files.
