### ISSUE TITLE
Preserve data reported as "modern"

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#49]
Currently, the QAQC tool will only accept numeric values in the fraction modern column. However, several studies report layers as "modern" rather than providing a fraction modern greater than 1. The current approach is to delete these cells and leave them blank, as though there was never any data there at all, but with this we end up losing some information. I understand that there is not much value in this information, but even knowing that the fraction modern is greater than 1 can potentially provide some constraint beyond having no data at all. Is there any way to preserve this information?

**Comment by greymonroe** [comment]
"modern" could be recorded as "Inf" which is still numeric

**Comment by jb388** [comment]
Seems like a good solution. Just need to make sure we document all these conventions!

**Comment by alkalifly** [comment]
I entered "Inf" (with a capital I) into the lyr_fraction_modern column, and it still fails QAQC with
	WARNING values greater than accepted max in lyr_fraction_modern column

**Comment by jb388** [comment]
Thought I had dealt with this, but apparently not. Should be fixed now.
