### ISSUE TITLE
QAQC - need check for correct hierarchy

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#50]
Some files have been making it through QAQC with inconsistent hierarchical names - very problematic!

Examples from the incubation tab:
(where there is an impossible combination of profile & layer listed)
Lawrence_2015 (profile: CWEE_1_2009     layer: CWEE2_Litter)
Morris_unpub(profile: Control_Under..., layer: N+Paddition....)

Maybe we could add another check to the QAQC using dplyr::anti_join or a similar function to ensure that the hierarchy is observed on all tabs?
Example:
anti_join(ISRaD_data$incubation, ISRaD_data$layer)  picks up these issues & could be repeated across tab combinations

**Comment by jb388** [comment]
OK, fixed this. However, could still be discrepancies between profile/site name combos on the flux tab, since profile names are not required. In a similar vein, there could be fraction/layer name discrepancies on the fraction tab, as frc_name is non-required.

**Comment by jb388** [comment]
Additionally, row indexes aren't being returned from layer/incubation mismatches.

**Comment by greymonroe** [comment]
any updates on this?

**Comment by jb388** [comment]
no updates, but I'll look into it.
