### ISSUE TITLE
Duplicate record QAQC for unique ID fields

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#55]
Since we added unique ids (xxx_name fields) to the flux, incubation, and interstitial tables, it seems reasonable to add a couple lines to QAQC to check for duplicate entries---which should not be allowed. This should enable us to keep track of replicates better at their respective spatial/temporal scales. Thoughts?

**Comment by greymonroe** [comment]
Sounds good, we could define duplicates as identical rows or those with the same identifiers. Which do you think?

**Comment by jb388** [comment]
I would use the identifiers (xxx_name). My thought is that people may enter reps with the same name, so they may have different values in some of the other fields.

**Comment by greymonroe** [comment]
@jb388 can you specify the line numbers where this is found in the current QAQC function code

**Comment by jb388** [comment]
229:234, 284:290, 339:344, 392:398, 459:471, 531:537

I can also work on this---I suspect this is an easy fix.

**Comment by greymonroe** [comment]
sounds great

**Comment by greymonroe** [comment]
Looks like this has been completed
