### ISSUE TITLE
flat file fix

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#58]
@aahoyt @alkalifly @ShaneStoner @coreylawrence @greymonroe @ktoddbrown 
Before the Powell Center meeting we need to generate an accurate flat version of the database. The current "flat" version is not accurate (contains duplicate records). 

Kathe, Alison, and I wrote a script for it, but the code is not in the compile function at the moment.

**Comment by jb388** [comment]
Update: I compiled the new version of the database with all the "ready for github" files, and uploaded a flattened csv that I generated using a slightly modified version of the 'flatten' function. However, this version won't be served by the website as it's still in dev.

**Comment by ktoddbrown** [comment]
We could just provide a function ie 'generate flat data' that returns a single dataframe. This will allow us to 'fix' the function as needed and reduced duplication of data in the package.

As far as the algorithm goes. There are some data tables that are heirartical and those should be joined using dplyr::join functions and then the resulting sheets should be bound together using dplyr::bind_rows. Or at least that would be my approach. @aahoyt I think this was more or less the approach we talked about earlier. Thoughts?

**Comment by aahoyt** [comment]
Yes, that's the approach we discussed, and Jeff is using the same approach based on shared conversations.

Currently the compile function is setup to generate a flat file as one option, so we need to remove that if we are just going to go with a separate flatten function. 

In the meantime, we should get Jeff's correct flat file to be served on the website by Monday (or change these functions by then).

**Comment by jb388** [comment]
Currently no flat file is being served from the github repo as the duplicate issue isn't completely ironed out. Once duplicate rows at the terminal nodes (fraction, flux, incubation, interstitial, layer) are eliminated, a simple flatten function (as Kathe and Alison mentioned) can be implemented.

**Comment by jb388** [comment]
@greymonroe can you update the compile function so it doesn't write out the flat file?

**Comment by greymonroe** [comment]
Yes, the new compile function on the dev branch does not write out the csv
