### ISSUE TITLE
“New beta release?”

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#59]
@aahoyt @alkalifly @ShaneStoner @coreylawrence @greymonroe @ktoddbrown @crlsierra
Just checking in about the status of our next planned beta release (per Corey's email). Are we ready to merge the dev branch with master? Any other changes we want to make? E.g. fixing the flat file, etc? Let's set a deadline for this. Tomorrow?

Updates since the last release include: minor template/template info changes, updating and adding entries to ISRaD_Data (from "ready for github" folder on Dropbox), updating entries currently on github, adding line references for warnings during QAQC, commenting out second QAQC call in compile.

**Comment by ShaneStoner** [comment]
From the email I just sent:

> Essentially, there are 76 new templates (as of this writing) that have passed the dev version of the QAQC that are not yet on Github. Jeff is currently working on making minor updates to all the templates that are currently on the Github so that they will pass the dev version of QAQC. That should give us 67 + 76 = 143 templates ready to go for the beginning of the Powell Center meeting.

Paul spent a lot of time sorting through the Yujie compilation, and we either got them to pass QAQC and are thus now in the Ready_for_Github folder, or they still need work and have be moved to the Entries_in_Progress folder. Claire Treat's compilation still requires a bit more work. I don't believe any of it will be included in this batch, but I could absolutely be wrong.

We believe that there should be no problems with merging master and dev tomorrow, once all the above changes are made. This will include a maximum amount of data and up-to-date functions in the R package. Hopefully everyone (especially Grey and/or Kathe) has time to review the current state of the github dev branch and check that there won't be any major issues with merging with the master branch. We will also include new compiled flat, list, and summary files from the latest iteration of the database when we merge the two branches tomorrow morning (Germany time).

Paul has been working on a walk-through for those who have never used the database or R package before. This will hopefully also be available by Monday. It's done a good job of highlighting things that could be modified down the road to improve user experience.

If anyone has recommendations or other ideas for how to structure the merging of these changes, please let us know. If a new branch or something else would be preferable, we could do that. We also need to decide if this is a "release" in the Github sense, and if so I think Grey is the best one to make that happen. 

>

**Comment by coreylawrence** [comment]
Ok. It looks like we haven't merged the dev with master as of now (Friday 12PM MT) but hopefully we can make that happen on Monday. I don't like the idea of having 100% more templates completed and passing QA/QC then are currently in the database. At this point, i am not sure I know the best approach (i.e., new branch, or new release, or?) so we just need to decide and make it happen. Please add any additional thoughts on this here and then we will lean on Grey to initiate the process (whatever we decide that should be).

**Comment by jb388** [comment]
Speaking for the MPI contingent, I think we were waiting on a go-ahead from Grey as we thought it possible we would breaking something we hadn't thought of. Obviously as things are functional on the dev branch, they should also be functional on the Master branch. The only issue I see is that the user guide at the website will need to be updated (new ref argument, and I think the report function also needs some attention). But those are minor issues against the massive increase in data. We can go ahead with things using the dev branch (everyone will be able to access all the new data), but seems like we should also just go ahead and merge dev with master.

**Comment by coreylawrence** [comment]
Merged. Issue can be closed.
