### ISSUE TITLE
Improvements to QAQC

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#62]
Some things are making it through QAQC which should not. Bundling previously suggested improvements & additional suggestions here:

(1) Check for unique name combinations for all "terminal nodes":
-site/profile/flux 
-site/profile/layer
-site/profile/layer/frc
-site/profile/layer/inc
-site/profile/interstitial
-Addressed in Issue #55 
-This should enforce more consistent handling of replicates. 

(2) Ensure that combinations in hierarchy are correctly entered
-Use antijoin to check all above cominations
-Addressed in Issue #50

(3) Check for any ambiguities in joins 
-Joining up the hierarchy (eg left_join(frc, layer)) should not create any new rows if data is entered correctly.
-Check to each join to ensure the number of rows stays the same, and throw an error in cases where additional rows are created. Indicates data ambiguity which needs to be corrected. These cases are currently slipping through

(4) Check lyr_name on incubation tab against possible layers on layer tab
-Ex: "bulk" should not pass QAQC (currently many of these are getting through)

(5) Similarly, check frc_input against possible layer or fraction names and require a match

**Comment by aahoyt** [comment]
Agreed!

**Comment by aahoyt** [comment]
As discussed- Add QAQC check for unique coordinates at all sites or fails QAQC with error message:
"Sites with the same coordinates should be re-categorized as profiles" (or similar)
(and 5 or 10km threshold?? )

**Comment by jb388** [comment]
didn't add message but added QAQC check
