### ISSUE TITLE
DOI check slow/inconsistent

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#63]
The DOI check in the QAQC is very slow. Additionally, it sometimes fails with DOIs that have passed in the past. I propose that we consider making the DOI check an optional component of the QAQC, which we would set to FALSE for the compile function. 

Since data can only be ingested into ISRaD by a member of the ISRaD team, we could run the DOI check for datasets separately before we ingest to make sure they work.

**Comment by ShaneStoner** [comment]
I have had this thought as well. Makes sense to me. I think the web tool QAQC should always check DOI, though.

**Comment by jb388** [comment]
Is there anyway to set this parameter to FALSE when compiling? More efficient for development.

**Comment by greymonroe** [comment]
fixed in last commit
