### ISSUE TITLE
Embedded list object not up to date

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#65]
The object "ISRaD_data" in the master version of the R package is not up to date. (Only 68 entries, not 145).
@greymonroe The excel object "ISRaD_list.xlsx" in the ISRaD_data/database directory is up to date, just not sure how to make it so this object is embedded in the ISRaD package.

**Comment by greymonroe** [comment]
fixed in last commit

**Comment by greymonroe** [comment]
hmm what did it look like?

**Comment by jb388** [comment]
@greymonroe fixed it
