### ISSUE TITLE
errors in variable type casting

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#66]
Currently the frc_fraction_modern is coming in as a character string, when it should be numeric. There may be other similar issues.

**Comment by aahoyt** [comment]
ACTUALLY HAPPENING FOR EVERYTHING! 

(didn't use to be the case...)

**Comment by greymonroe** [comment]
please restart R (and dont save current environment if prompted) then run:
```
install_github("International-Soil-Radiocarbon-Database/ISRaD", ref="dev")
library(ISRaD)
str(ISRaD_data)
```

**Comment by greymonroe** [comment]
Im interested to see what the output is

**Comment by greymonroe** [comment]
fixed
