### ISSUE TITLE
check Treat S2 and S3 files

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#70]
@aahoyt Can you take a look at the converted S2 and S3 files which have been converted to the template. I wanted to check that they make sense before I try to combine them. Thanks

**Comment by greymonroe** [comment]
they are found in Dropbox/ISRaD_data/compilations/Treat/raw

**Comment by aahoyt** [comment]
We started working on the Treat synthesis files again over AGU. I brought Claire Treat up to speed on it, and she's going to do a more rigorous look through the current files.
