### ISSUE TITLE
Creating filled ISRaD_data (adding transformed/filled variables)

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#73]
Need to write function that creates transformed variables or fills in NA values...

``` 
ISRaD.fill<-function(database=ISRaD_data){

#series of transformations and backfills

return(database)

}
```

_**Conventions:**_
**New variables** must be named using traditional naming conventions (ie frc_XXX for variables in fraction tab). They must also be adequately described. We need a document that explains in human readable terms what each new variable is.

**Back filling variables** can be done if the components come only from the data in the database object and universal equations.

**Comment by aahoyt** [comment]
See vignettes folder for backfill examples

**Comment by aahoyt** [comment]
First things to backfill:
-Fill dates from higher levels of hierarchy
-Fill profile coordinates from site coordinates

**Comment by aahoyt** [comment]
Next level: 
-Fill 14c columns from fraction modern & vice versa
-Will require filling columns on many layers of hierarchy, including 14c, 14c_sd and 14c_sigma columns, etc
-Single example available in vignette, needs to be expanded to a function to apply across the list

**Comment by jb388** [comment]
> Next level:
> -Fill 14c columns from fraction modern & vice versa
> -Will require filling columns on many layers of hierarchy, including 14c, 14c_sd and 14c_sigma columns, etc
> -Single example available in vignette, needs to be expanded to a function to apply across the list

Done.

**Comment by jb388** [comment]
> First things to backfill:
> -Fill dates from higher levels of hierarchy
> -Fill profile coordinates from site coordinates

Done.

**Comment by jb388** [comment]
Also added delta_delta fx.
