### ISSUE TITLE
Explore potential to incorporate Geo Sample Number reference

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#77]
We should consider potential to adopt the International Geo Sample Number (http://www.geosamples.org/aboutigsn) for identification of soil layers, which could be used to better to track replicate and composite sample details.

**Comment by greymonroe** [comment]
we could add a column in layer tab. thoughts?

**Comment by jb388** [comment]
Added "lyr_igsn" to template/info files.
