### ISSUE TITLE
"Ingested" tab of Google doc contains many un-ingested entries

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#79]
I'm not sure who is looking after the Google spreadsheet these days, but it seems we now have multiple tabs for different status entries. This is a nice feature. However, there are still a lot of entries in the "Ingested" tab that haven't been ingested. Most, if not all, specify say "Entries_In_Progress" for the "Status/Folder" and have template files that are now in ISRaD/ISRaD_data_in_progress on github.

Should these entries be moved to the other tab?

**Comment by coreylawrence** [comment]
I just addressed this issue and am going to close this issue. However, I will leave the related issue #80 open for feedback.
