### ISSUE TITLE
Include Yujie's data in compiled database

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#8]
It sounds like this will involve:
-Generating templates from Yujie He's compilation for each dataset
-Manual removal of duplicate templates (some have been added as new flux, fraction or incubation data is added)
-Final templates added to data folder for compilation

**Comment by jb388** [comment]
This is just a ping for a status update.

**Comment by greymonroe** [comment]
ISRaD_data/Compilations/Yujie/converted/ now contains the converted files for datasets compiled by Yujie. 
Similarly, ISRaD_data/Compilations/Treat/converted/ contains the files for datasets compiled by Claire Treat
