### ISSUE TITLE
Google doc "Ingested" tab reverted to previous version

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#80]
It seems that the "Ingested" tab of the Google spreadsheet had the first column sorted independently of the other columns, so the information on that tab was incorrect. Fortunately, Google docs keeps old versions, and I was able to find where in the history it went wrong. I can see that the version from October 11, 10:19 AM (not sure if that pacific or universal time) is correct, and the next version, from three hours later, is incorrect, so I renamed the versions in Google accordingly.

To remedy this, I replaced the contents of the tab with the  last correct version. As a result, any changes that were made to this tab since October 11, 2:20 PM have been wiped out, and need to be made again. I looked through the file history, and saw the following changes:

1. The four entries for Hicks-Pries got notes saying "needs fixing, missing data" on October 12, 11:03 AM

2. The entry name for the bottom row (the most recently entered file, which indicates Bastian is working on it) was changed October 12, 1:08 AM

NOTE: I did NOT try to re-create any of those changes, because they were made when the table was totally incorrect, so I can't be sure what they were actually intended to be. Unfortunately, all of the changes in Google are anonymous, so I can't tell who made them (is there some way we can fix that?). So if you made those changes, or think you may have made any others, please check this tab and re-make whatever changes got wiped out.

**Comment by coreylawrence** [comment]
Ok Cats and Kittens.
I just went through this file and completed the following: (1) All *In Progress* entries that were included in the `Ingested` tab have been identified and moved to appropriate tab. (2) Duplicate entries in the `In Progress` tab  that resulted from step have been identified and merged. I have retained one additional column, called *Status* in the `In_Progress` tab, which corresponds to the original folder designation from the Jena Hackathon. 

Please note the following rules pertaining to this document: 
_(1) Thou shall not place any entry in the `Ingested` tab unless it is actually ingested and available in the `ISRaD_data` folder on Github.
(2) Thou shall not add columns to any of the tabs
(3) Thou shall update these lists when changes to the file status have been made_

As it pertains to the rules above, when an *In_Progress* template has been completed - meaning it is passing QA/QC and ready for ingestion. It should be noted in the status column of the `In_Progress` tab. Once the dev branch has been recompiled and that file shows up in the `ISRaD_data` folder, then and only then should it be moved to the `Ingested` tab.

**Comment by aahoyt** [comment]
Excellent work updating the sheets! Thanks!!
I promise to abide by the tenets (and posted them on the document as a reminder)

Also, good to know about rolling back the Google doc for future reference.

**Comment by coreylawrence** [comment]
I wonder if we should just remove the controlled datasets (i.e., "Private > Otherwise_passing_QAQC") from this list and track those somewhere else?
