### ISSUE TITLE
Temporary Home for Completed but Not-Yet-Ingested Templates

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#81]
In working through the google document for tracking entries, I was wondering how we are/should be handling entries that are either (1) new or (2) in progress and are otherwise passing QA/QC and ready for ingestion? 

For example, lets say someone downloads a file from the `ISRaD_data_in_progress` folder and makes the necessary modifications so that it is complete and passing the QA/QC. When that file is emailed to _info.israd@gmail.com_ and has been reviewed, where does that file go before it is officially added through a recompile? 

Alternatively, if I (an expert reviewer) am satisfied that an entry I have working on is ready to be compiled, where should I put it (if I do not plan to recompile the database right away)?

**Comment by coreylawrence** [comment]
Or can these files just be added to the `ISRaD_data` int the Dev branch?

**Comment by aahoyt** [comment]
Adding to ISRaD_data in the Dev branch sounds good to me, if it is passing QAQC and has been through expert review. That is effectively what we've been doing I think, and avoids more folders.

**Comment by jb388** [comment]
@coreylawrence @aahoyt Agreed!

**Comment by greymonroe** [comment]
yes, the workflow is that files are...

1. emailed to info.israd@gmail.com
2. sent out for expert review
3. added to ISRaD_data_files
4. the database is recompiled with ISRaD.build()
5. changes are committed to github
