### ISSUE TITLE
ISRaD.extra.delta_delta import pkg

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#84]
@greymonroe 
The ISRaD.extra.delta_delta function requires the forecast package to work. The package is currently called by #'import forecast, but apparently that isn't working. Is there another way to make sure a package is loaded?

**Comment by greymonroe** [comment]
to fix this you need to update the documentation of the R package and reinstall.

while your working directory is in the repo run **devtools::document()*

This should update the NAMESPACE file.

You should also goto the DESCRIPTION file and add forecast to the "requires" parameter.

**Comment by jb388** [comment]
Ok, thanks. I'll follow up.

**Comment by greymonroe** [comment]
K let me know if you run into any issues

**Comment by jb388** [comment]
Seems to have worked. Thanks!
