### ISSUE TITLE
web QAQC flx_name error

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#85]
@greymonroe Templates that pass QAQC in R are failing the web-based QAQC with an error related to the new flx_name column. The error isn't a standard "warning" in the QAQC report, but rather a server error:

Server error: object 'flx_name' not found

In call:
.f(.x[[i]], ...)

Strangely it's only the flx_name column that causes the error, not the ist_name or inc_name columns that were added at the same time. Additionally, I merged dev with master this morning, so the QAQC script should be the same for both web and R. Any insight?

**Comment by greymonroe** [comment]
@jb388 Do all templates produce this error? If not, do the ones that are failing contain the "flx_name" column? 

I noticed in the QAQC function there are new lines that call on columns directly. For example, line 289, refers to flx_name and if that was not found in the data file being checked it might cause the code to break.

**Comment by jb388** [comment]
All the templates missing "flx_name" do. I called the column directly because I was getting errors stemming from the plot name column. I'll have to think about a work around.

**Comment by greymonroe** [comment]
A quick fix would be adding an if statement preceding that line which would check if the columns were present before running the code

**Comment by jb388** [comment]
Yeah, that was my thought, too. Alternatively I was looking into how to select the relevant columns without referencing them directly. But I think it's easier to add the if statement, even though I prefer to keep the code consistent---makes it easier to look at.

**Comment by jb388** [comment]
Ah, turns out it's easy. Just had the syntax wrong.

**Comment by jb388** [comment]
Or not. But easy enough to add an if statement.
