### ISSUE TITLE
Management of info.israd account

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#87]
@aahoyt @greymonroe @ShaneStoner @coreylawrence 
Yesterday I expert-reviewed and uploaded all the templates sent to the info.israd account (and today I reviewed and uploaded the newest one from Sophie). As I was doing so I realized we don't have a system in place to track that activity---i.e. responses/follow-up. I'm not sure it's necessary (we can always check github and look at the sent mail folder), but I thought I'd poll the group to see if you have any thoughts on the matter.

**Comment by aahoyt** [comment]
Thanks!!

It seems good to have people check it & reply whenever they are interested, but we probably need some sort of back-up system, especially for less active periods, so that things don't fall through the cracks. I don't know what the best way to organize that would be though...?

**Comment by jb388** [comment]
I created a google doc only accessible to the info.israd account in order to keep track of submissions. The current format seems to work, but if you have any ideas about how to improve or change it, go for it.
