### ISSUE TITLE
Protocol for ISRaD_data_in_progress

### ISSUE THREAD

**Issue by alkalifly** [International-Soil-Radiocarbon-Database/ISRaD#88]
Now that all of the "in progress" entries have been moved from Dropbox to Github, how exactly should I proceed with completing the ones I was working on?

It seems a bit counterintuitive to have binary files in a git repository that are intended to be changed. For example, the ISRaD_data_in_progress folder is now 6.1 MB, and most if not all of those files will be changed before they are ready for ingestion. Since git keeps every version of each binary file, this means that 6.1 MB of soon-to-be-useless data are forevermore part of the repository. It's not too bad if this is only these remaining files left over from the hackathon. But it's probably not a good long-term staging area for templates in progress.

In the meantime, I want to proceed with care as I finalize some of the pending files in this folder. Should I create a new branch, update the files there, and then create a merge request? If so, should I move the file into the ISRaD_data folder? Or should I simply submit a completed spreadsheet to israd.info@gmail.com and let that replace the in progress version?

**Comment by jb388** [comment]
The idea behind moving the in progress files to github was to centralize the files that multiple people had been working on. While space might be a concern eventually, we decided we'll cross that bridge when we come to it...This is NOT the place to upload any files that you are working on, only the ones from Yujie's compilation or ones that multiple people had been working on.

Once a completed file is done and passes QAQC, you should just follow the normal procedure of submitting the template and the .txt file from the QAQC output to israd.info@gmail.com. I suggest adding a note to the in-progress google doc that makes this clear, e.g. "submitted to israd.info/needs expert review". Once expert review is completed, one of the data maintainers (i.e. those who have access to the israd.info account) will move the record from the 'in-progress' tab of the google doc to the 'ingested' tab.
