### ISSUE TITLE
Package installation -requires "raster" package

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#91]
Package installation now requires people to first install "raster" package. This is a new issue that has been coming up during installation (4/4 people installing ISRaD package today experienced it). Not exactly a bug, since the package still works after installation, but seems to be a consistent issue for new users.

Perhaps it is caused by new code in the ISRaD.extra.geospatial?

Comment from Karis:
It told me I needed the package “raster”. I installed and loaded it. I tried installing the ISRad package again and it worked, but gave the following warning: “Warning: replacing previous import ‘tidyr::extract’ by ‘raster::extract’ when loading ‘ISRaD’”. So I re-installed tidyr package. I tried re-installing tidyr and going through steps 1 and 2 again, but got the same warning.

**Comment by jb388** [comment]
Should be fixed. If not let me know.
