### ISSUE TITLE
Protocol for addition of new colomns

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#95]
@coreylawrence @greymonroe  @aahoyt @ShaneStoner 
We have discussed the inevitable need to add new (non-required) columns many times over the past year. But to my knowledge, we still don't have a protocol in place.

The most recent examples are:
1) pre-treatment column for 14C data
2) summation columns for sequential mineral dissolution, e.g.:
lyr_fe_al_py (sum of pyrophosphate extractable Fe and Al, often reported together);
lyr_noncrystalline (non-crystalline mineral content, e.g. sum of all ammonia oxalate extractable Fe, Al, Si).

Perhaps we can devise a protocol for how to deal with the new column issue more generally at the upcoming hackathon. Accordingly, input from those who will not be at the hackathon is especially desirable--Corey, Kate, others?

**Comment by greymonroe** [comment]
Adding non-required columns is easy and wont break anything. If a column is required or if we change the name of an already existing one, things get tricky. 

If someone sees the need to add a column it still should be reviewed. A suggestion is for the proposed column to be posted here in the issues page on github and a grace period of 5 days will be given for people to raise objections. If there are no objections, the column can be added to the template file and template info file. It will be then committed to the github repo.
