### ISSUE TITLE
files in ISRaD_Data are failing QAQC

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#97]
There are some files that are failing QAQC but are found in the ISRaD_data folder. 

McClung_de_Tapia_2005.xlsx ...failed QAQC. Check report in QAQC folder.
McFarlane2013Porras2017TrumboreUnp_inc.xlsx ...failed QAQC. Check report in QAQC folder.
Hatton_2012.xlsx ...failed QAQC. Check report in QAQC folder.
Sollins_2009.xlsx ...failed QAQC. Check report in QAQC folder.
Trumbore_1995.xlsx ...failed QAQC. Check report in QAQC folder.
Trumbore_1996Koarashi_2012Marzaioli_2010.xlsx ...failed QAQC. Check report in QAQC folder.

These files need to be run on the most recent QAQC. If they fail, they need to be moved to "in_progress."

**Comment by jb388** [comment]
fixed McClung

**Comment by jb388** [comment]
fixed McFarlane etc.

**Comment by jb388** [comment]
fixed Hatton

**Comment by jb388** [comment]
fixed Sollins, Trumbore_1995, and Trumbore etc.
