### ISSUE TITLE
inconsistencies between template info and template files

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#98]
the output from compile returns these errors: 

**Checking compatibility between ISRaD template and info file...
 metadata ...
 site ...
 profile ...
 flux ...
 layer ...
 interstitial ...
 fraction ...
	WARNING column names unique to template: frc_fe_al_py
 incubation ...
	WARNING column names unique to info file: inc_name**

need to change info and template file so that they are compatible

**Comment by jb388** [comment]
Fixed.
