### ISSUE TITLE
Update Description file

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#99]
The DESCRIPTION file needs to be properly filled in before we can submit to CRAN. 

**Title: What the Package Does (one line, title case)
Version: 0.0.1.0000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).**

Can we pull these from the paper?

**Comment by jb388** [comment]
Sure---seems fine to pull from paper.
